[장바구니 협업 step2] 루루(송지은 ) 미션 제출합니다.
woowacourse/react-shopping-cart-prod pull request #126
Opened 2023-06-02 06:30 UTC by hafnium1923

2023-06-03 10:32 UTC, hafnium1923 commented
안녕하세요 티케! 에디에게 달아주신 리뷰를 보다가 의문점이 들어서 질문드립니다!ㅎㅎ

1. BrowserRouter 
[커밋링크](https://github.com/woowacourse/react-shopping-cart/pull/238/files#r1204512186)

링크 걸어주신 router 사용에 대한 해당방법을 저는 router 사용에 대한 최신문법이라고 알고 있는데 현재 사용하고 있는 
```
<Routes>
        <Route path="/" element={<ShoppingPage />} />
        <Route path="/cart" element={<CartPage />} />
</Routes>
``` 
이것과 비교해서 어떤 좋은 점이 있는지 궁금합니다. 추측하기로는 <Outlet />을 사용할 수 있어 페이지 이동에 대한 관리가 편해진다는 것 인데 맞을까요?

2023-06-06 06:08 UTC, devhyun637 requested changes
안녕하세요 루루~ 미션을 일찍 했는데 리뷰가 늦어 죄송합니다 🙇‍♀️
전반적으로 코드의 일관성이 있어서 보는데는 깔끔해서 좋았습니다. 몇가지 소소한 피드백을 남겨두었고, Step1에서 못했던 리뷰들에 대해서 전반적으로 요 메세지에 남겨둘게요!

### UX관련
- 상품을 담았을 떄, 담았습니다~ 를 알려주는 `snackbar`가 있다면 좋을 것 같아욧
- 쿠폰페이지는 코멘트도 확인해주세요~ 그리고 쿠폰을 발급할때마다 화면이 깜빡이고 맨 위로 올라가는 건 의도한 걸까요? 
- 장바구니가 비어있는 상황에서 선택삭제가 가능한 부분이 어색하네요~ 상품이 없다는 걸 나타내주는 안내문구도 함께 있으면 좋을 것 같아요
- 쿠폰 `modal`에서도 쿠폰에 마우스를 올리면 `pointer`로 해두면 어떨까요?
- 새로고침이 대응이 안되어있어요~ 404가 뜹니다
- `favicon`을 넣어보는 것도 좋겠네용

### 코드 관련
- `package.json`의 의존성 부분에 대한 정리를 잘 해주셨더라구요! 👏👏
- `react-query`를 사용하였던데 어떠신가요? 어떤 점 때문에 사용했나요? 왜 데이터패칭 라이브러리로 `react-query`를 사용했나요?
- 전반적으로 어떤 부분을 상태관리를 하려고 했는지, 상태관리는 어디까지 프론트에서하는게 좋을지 고민을 해보면 좋을 것 같아요. 이 부분에 대해서 코멘트 남겨주시면 더 좋을 것 같구요!
- `react-query`를 사용한 부분에서 API 통신임에도 불구하고 에러 처리가 어디에도 없어요~ [공식문서](https://tanstack.com/query/v4/docs/react/guides/query-functions#usage-with-fetch-and-other-clients-that-do-not-throw-by-default) 참고해주세요! 실제 코드에서도 `try`라는 키워드를 검색해보았는데 전혀 나오지 않더라구요 🤔 또, `ErrorBoundary`도 없어서 에러핸들링이 전혀 안되어있는 점이 아쉬웠어요ㅠ.ㅠ
- `hook`에서 `useQuery`를 사용해서 API통신을 하고 있는데, 추상화가 가능할 것 같아요. 거의 형태가 비슷하고, 요청 url, queryKey만 다른것같아서요!
- `Button` 컴포넌트에 `type` 속성을 받을 수 없네요..! 즉, `<Button>`은 `<button>`의 기본 속성을 대부분을 활용하지 못한다는 의미이죠. React의 `HTMLAttributes`를 활용해서 기본적으로 `html`이 제공해주는 속성을 활용할 수 있게 해줍시당

### 기타
- PR 메세지에 쓴 것을 REAME에 쓰면 정말 멋있을 것 같아요. AWS에서 서버를 내리면 이 프로젝트를 로컬로 봐야하는데 영상으로 남아져있을 테니깐요!
- 한번 aws로 배포해보았습니다! >> 너무 멋있어요!! 👍👍

### 질문 & 답변
> 소통관련해서 질문드립니다. 이번 미션을 진행하면서 감정적으로 상하는 일이 있었습니다. 서버연결에서 발생한 오류를 해결하는 과정에서 크루가 기분이 나쁜
 말투로 저에게 따지듯 말했던 일이었습니다. 다만 저희 팀 크루가 아닌 처음 본 백엔드 크루였기 때문에 제가 직접적으로 불쾌함을 표현하지 못하고 같은 팀 크루에게 전달을 부탁드렸는데, 저만 참으면 되는 일을 괜히 팀원에게 알려서 팀원들도 불편하게 한 것이 아닐까 하는 고민이 듭니다. (당연히 전달을 부탁드린 후에는 웃으면서 미션을 진행하긴 했습니다.) 혹시 티케는 일을 하시다가 기분이 나쁜 일이 일어나면 어떻게 해결하시는지 궁금합니다.

되게 어려운 질문이네요….. 우테코 리뷰하면서 받은 질문중 제일 어려운 질문이에요.

“크루가 기분이 나쁜 말투로 저에게 따지듯 말했던 일” 
어떤 상황일지는 모르지만 충분히 기분이 나쁠만하는 상황이었을 것 같아요.  

“같은 팀 크루에게 전달을 부탁드렸는데, 저만 참으면 되는 일을 괜히 팀원에게 알려서 팀원들도 불편하게 한 것이 아닐까 하는 고민이 듭니다” 
저는 이와 같은 대처도 좋다고 생각해요. 마음고생이 심했을텐데 고생많으셨습니다.(토닥토닥) 

제가 실무에 들어와 일을 한 지 만 1년밖에 안되긴 했지만, 서버한테 응답이 제대로 안온다고 하면 빠르게 대응해주셔서 오류 발생으로 인해서 기분이 상한적은 없었던 것 같아요! 또 오히려 취준 혹은 사이드 프로젝트를 할때보다 실무에서 기분이 나쁜일이 훨씬 적었던 것 같아요. (사회화된걸까요..ㅎ..ㅋ..) 하지만 만약 기분 나쁜일이 생긴다면 먼저 제가 놓친게 무엇인지 생각해보고, 기분이 나빴다는 걸 바로 직접적으로 이야기하기보다는 상급자와 논의 후 상급자의 입을 통해서 말할 것 같아요. 하지만 우테코니깐 이런 갈등을 ‘직접’해결해볼 수 있는 경험도 흔치 않을테니 다음부터는 마음이 좀 가라앉은 후 해당 크루에게 커피한잔 하자고 하면서 혹은 DM으로 ‘어떠한 점이 기분이 안좋았다.’라고 말하면서 이야기해보는건 어떨까요? 그 크루도 이러한 협업이 처음이라서 어떻게 대처해야할 지 몰랐을 수도 있으니깐요. ~~그렇다고 해서 기분 나쁜 말투로 말하는게 정당화 되지는 않지만요... 넘무해~~

>  데이터의 신뢰성이 높은 쪽으로 변경하시나요 아니면 변경시간또한 비용이라 생각하고 그대로개발

중간에 명세가 바뀌어야한다면 당연히 저는 데이터의 신뢰성이 중요하기 때문에 코드를 바꿀 것 같아요. 하지만 바꾸는 작업이 너무 커서 작업시간이 무리가 크다고 싶으면 그대로 개발을 하고, 추후 변경을 고려하는 편이기도 하구요. 사실 그런건 제가 정하는게 아니라, 정해진 배포날짜와 QA기간에 따라서 기획자분께서 조정을 해주시곤 하는데, 무조건 기간 내에 나가야하는 것이 있고 백엔드의 명세 변화도 필수적이라고 하면 최대한 맞추는 편입니다. 

> 에러가 터질때는 제 잘못인가 하는 두근거림도 있었지만

이제야 말하지만 우테코 협업 미션 전에 간단한 서버와 통신 미션때 페어와 함께 의도하지 않게 서버 터트린적 있..ㅎㅎㅎㅎ 재밌게 했다니 다행이네요~

2023-06-06 06:08 UTC, devhyun637 commented on src/index.tsx
> +const router = createBrowserRouter(
관련해서 남겨주신 질문과 관련해서 `createBrowserRouter`를 추천한 이유는 매우 단순한데요, 공식문서에서 추천하기 때문이에요. 사실 기존의 `BrowserRouter`에서 제공되는 기능만 추가된 거라서 '굳이?' 라는 생각이 든다면 적용을 하지 않아도 되겠지만 공식문서에서  

> "We recommend updating your app to use one of the new routers from 6.4. The data APIs are currently not supported in React Native, but should be eventually." 

라고 말하는건 아마 추후에는 `<BowserRouter>`를 f/o 시킬수도 있다는 의미가 될 수 있으니, 굳이 추천하는걸 쓰지 않아야하는 이유도 저는 없다고 생각해서 리뷰를 드렸습니다 🙇‍♀️

2023-06-06 06:08 UTC, devhyun637 commented on src/abstract/constants.ts
폴더명이 왜 `abstract`일까요?

2023-06-06 06:08 UTC, devhyun637 commented on src/components/common/header/Header.tsx
>            <Text color="#FFFFFF" size="largest" weight="bold" lineHeight="58px">
1. 제가 이전 크루한테도 말했는데, `<Text>` 컴포넌트가 전부 `<p>`로만 이루어져있는게 맞을까요? `<Header>` 부분은 더욱이 제목태그로 이루어지는 게 맞지 않을까요? emotion에 해당 속성을 제공하는 기능이 있으니 찾아보시고 적용해보세요~

2. (선택) 나중에 프로젝트 할 때에는 `font-size`, `line-height`를 함께 엮어서 `size`로 관리해도 좋겠다는 생각이 드네요~

2023-06-06 06:08 UTC, devhyun637 commented on src/components/common/header/Header.tsx
>    background-color: #333333;
```suggestion
  background-color: #333;
```

도 가능합니다~

2023-06-06 06:08 UTC, devhyun637 commented on src/components/common/Selector/Selector.tsx
> +      <option>홍고</option>
왜 여기는 emotion을 적용하지 않았을까요?

2023-06-06 06:08 UTC, devhyun637 commented on src/components/common/Selector/Selector.tsx
> +    navigation('/');
왜 홈으로 보내주는 걸까요?

2023-06-06 06:08 UTC, devhyun637 commented on src/components/common/Menu/Menu.tsx
> +        |
'|'는 css 가상선택자로 충분히 구현 가능해보이는데요!

2023-06-06 06:08 UTC, devhyun637 commented on src/components/common/Menu/Menu.tsx
> +      <EventInfo />
`<EventInfo>`와 `<UserOrderInfo>`는 추상화를 해볼 수 있을 것 같아요!

2023-06-06 06:08 UTC, devhyun637 commented on src/components/common/Menu/UserCartInfo.tsx
> +          {cartTotalQuantity && cartTotalQuantity > 99 ? 99 : cartTotalQuantity}
99는 상수로 선언해도 될 것 같아요~

2023-06-06 06:08 UTC, devhyun637 commented on src/hooks/useCartFetch.ts
다른 부분과 동일하게 `useCart` 파일명도 충분할 것 같아요

2023-06-06 06:08 UTC, devhyun637 commented on src/components/box/ProductItem/ProductItem.tsx
>    useEffect(() => {
cart에 아이템을 추가하거나 조정할 때 그냥 요청을 보내면 될 것 같은데, `useEffect`를 활용하는 이유는 무엇인가요?

2023-06-06 06:08 UTC, devhyun637 commented on src/components/list/CouponList/CouponList.tsx
> +  };
```suggestion
  if (isFetching) {
    return <LoadingSpinner />;
  }
  
  const addCoupon = async (couponId: number) => {
    addCouponAPI({ id: couponId });
  };
  
```

전반적으로 코드에 개행이 없는데, 개행을 넣어주세요 :)

2023-06-06 06:08 UTC, devhyun637 commented on src/types/types.ts
>  export interface ProductType {
`-Type` suffix를 붙이는 이유가 있을까요?

2023-06-06 06:08 UTC, devhyun637 commented on src/types/types.ts
저희팀은 Interface나 type의 속성에는 주석을 다는 편입니다. 그러면 어떤 데이터인지 알기 쉽더라구요!
<img width="245" alt="스크린샷 2023-06-06 오후 2 11 17" src="https://github.com/woowacourse/react-shopping-cart-prod/assets/59258239/4411e2a4-1f97-4472-a6fd-9501e0db9bcc">

2023-06-06 06:08 UTC, devhyun637 commented on src/components/list/CouponList/CouponList.tsx
> +                  : openModal({ title: '이미 발급된 쿠폰입니다.' });
추후에는 이런 안내는 `snackbar`, `toast`와 같은 `dialog`를 활용해봐도 좋을 것 같아요 :)
그리고 발행된 쿠폰에 대해서는 발급하기를 누르지 않아도 알 수 있게 아에 버튼을 비활성화 하든지, 아니면 쿠폰 옆에 표현을 해두면 더 좋을 것 같아요~

2023-06-06 06:08 UTC, devhyun637 commented on src/components/list/DetailList/DetailList.tsx
> +            <Button onClick={onDelete}>주문취소</Button>
이 두가지의 기능은 무엇일까요?.?

2023-06-09 01:22 UTC, hafnium1923 commented on src/index.tsx
> +const router = createBrowserRouter(
아하! 그렇군요 감사합니다!

2023-06-09 01:23 UTC, hafnium1923 commented on src/abstract/constants.ts
상수도 추상화의 일부라고 생각해서 폴더명을  `abstract`라고 지었습니다.

2023-06-09 01:43 UTC, hafnium1923 commented on src/components/common/header/Header.tsx
>            <Text color="#FFFFFF" size="largest" weight="bold" lineHeight="58px">
1. Text 컴포넌트는 p태그로 이루어지는 것이 맞다고 생각합니다. 왜냐하면 Text 컴포넌트는 여러 사이즈와 여러 굵기를 대응해야하기 때문에 특정 사이즈의 태그를 사용하는 것 보다 전체를 아우를 수 있는 태그를 사용하는 것이 Text 컴포넌트를 분리한 의미가 있다고 생각합니다. 그와는 별개로 header는 제목태그를 사용하는것이 옳다고 생각해서 바꾸었습니다. 

2. 넵! 한번에 size를 관리하는 방법도 연습해보겠습니다.

2023-06-09 01:49 UTC, hafnium1923 commented on src/components/common/header/Header.tsx
>    background-color: #333333;
디테일이네요! 같은 문자가 반복되는 색깔들을 축약형으로 바꾸었습니다. 눈으로 하나씩 확인한 거라 놓친 부분이 있을 수 있다고 생각됩니다

2023-06-09 01:54 UTC, hafnium1923 commented on src/components/common/Selector/Selector.tsx
> +      <option>홍고</option>
간단한 스타일이라고 생각해서 적용하지 않았습니다. 일관성을 위해 적용하도록 하겠습니다!

2023-06-09 02:01 UTC, hafnium1923 commented on src/components/common/Selector/Selector.tsx
> +    navigation('/');
서버를 로그인 한 하나하나의 유저라고 생각했습니다. 장바구니에서 A회원이 로그아웃하고 로그인을 한다고 B회원의 장바구니에 남아있지 않습니다. B회원이 로그인 했을 경우 B회원에 맞는 상품을 보여줘야하기 때문입니다. 그래서 유저를 바꾸었을 때 홈으로 이동하는 것이 자연스럽다고 생각해서 그렇게 바꾸었습니다.

2023-06-09 02:05 UTC, hafnium1923 commented on src/components/common/Menu/Menu.tsx
> +        |
아! 넵 적용해보았습니다!!

2023-06-09 02:10 UTC, hafnium1923 commented on src/components/common/Menu/Menu.tsx
> +      <EventInfo />
오 바로 적용해보았습니다!

2023-06-09 02:27 UTC, hafnium1923 commented on src/hooks/useCartFetch.ts
앗 저는 약간 fetch랑 일반 계산 로직이랑 헷갈릴 수 있다고 생각해서 fetch를 명시한것인데 꼭 바꿔야만 할까요..?  일관성 때문에 그렇다면 useProduct훅을useProductFetch 로 이름을 변경했습니다.

2023-06-09 02:52 UTC, hafnium1923 commented on src/components/list/CouponList/CouponList.tsx
> +                  : openModal({ title: '이미 발급된 쿠폰입니다.' });
앗 넵! 이번에는 일부러 발급 하고나서 다시 버튼을 눌렀을 때 발급한 쿠폰이라고 모달이 다르게 나오는 것을 확인하기 위해서 이렇게 진행했지만 추후에 비슷한 기능을 만들 때는 말씀해주신 조언 참고해 개발하도록 하겠습니다.

2023-06-09 02:55 UTC, hafnium1923 commented on src/components/list/DetailList/DetailList.tsx
> +            <Button onClick={onDelete}>주문취소</Button>
주문확정을 누르면 해당 주문에 사용되었던 쿠폰이 다시 발급가능상태가 되며, 백엔드 재량으로 자동적으로 금액대별 쿠폰이 발행되도록 하였습니다. ably나 zigzag의 기능을 참고하였습니다. 주문 취소를 누를 경우 주문목록에서 해당 주문이 삭제되고 주문에 사용되었던 쿠폰이 다시 발급된 쿠폰으로 돌아갑니다. (사용되었던 쿠폰 취소)

2023-06-09 03:04 UTC, hafnium1923 commented on src/types/types.ts
넵 타입에 주석을 추가했습니다.

2023-06-09 03:05 UTC, hafnium1923 commented on src/types/types.ts
>  export interface ProductType {
비슷한 변수명과 컴포넌트들이 많기 때문입니다. 타입과 다른 변수들이랑 헷갈리지 않기위해 suffix를 붙였습니다.

2023-06-09 03:28 UTC, hafnium1923 commented on src/components/box/ProductItem/ProductItem.tsx
>    useEffect(() => {
상품 목록을 처음 렌더링할 때 quantity의 값을 설정해주기 위해서였습니다.  다만 cartItemData의 값을 설정할 때 같이 진행해도 될 것 같아 아래처럼 바꾸었습니다.
```
  useEffect(() => {
    const existData = cartData?.find((cart) => cart.product.id === product.id);
    if (existData) {
      setCartItemData(existData);
    }
    if (existData) setQuantity(existData.quantity);
  }, [cartData]);

```

2023-06-09 06:29 UTC, hafnium1923 commented
안녕하세요 티케! 열심히 리뷰반영하고 돌아온 루루입니다~~😆
남겨주신 리뷰에는 코멘트나 이모지 남겨놨습니다. 아래는 PR 메시지로 주신 의견에 대한 답변입니다!(반영한 부분이나 코멘트 남긴 부분에 대해서는 답변하지 않았습니다)

UX관련
> 쿠폰을 발급할때마다 화면이 깜빡이고 맨 위로 올라가는 건 의도한 걸까요?

화면이 깜빡이는 것은 발행 여부에 대해서 다시 refetch 하기 때문입니다. 다만 맨 위로 올라가는 것은 제 의도가 아니긴합니다..ㅠㅠ 고치지 못했습니다.
> 새로고침이 대응이 안되어있어요~ 404가 뜹니다

해당 이슈는 aws에 router 설정을 안해두어 일어나는 것 같습니다. local에서는 발생하지 않는 것을 확인했습니다.

코드 관련
> react-query를 사용하였던데 어떠신가요? 어떤 점 때문에 사용했나요? 왜 데이터패칭 라이브러리로 react-query를 사용했나요?

처음은 페어 코드를 기반으로 했기 때문에 고치지 않고 그대로 사용했습니다. 하지만 사용하다 보니 일반적으로 fetch 구문을 사용한 것 보다 유용함을 찾을 수 있었습니다. 가장 큰 것은 하나의 데이터가 바뀌었을 때 다른 데이터들이 연쇄적으로 fetch 되어야할 때 입니다. 제 이전코드를 사용한다면 주문 완료 후 주문목록, 장바구니, 주문디테일 세가지 데이터를 fetch 하는 것이 불편할 정도로 복잡하게 설계해야 여러가지의 버그를 피할 수 있었습니다. 하지만 react-query에서는 queryClient.refetchQueries를 통해서 간단하게 해결할 수 있습니다. 두번째 이유는 비동기 작업 후 또 다른 비동기 작업할 때 데이터의 동일성을 보장해줍니다. react-query에 있는 onSuccess를 사용하면 fetch 진행 후 데이터 set을 하는것이 순차적으로 진행된다는 것을 보장해줍니다. 즉, 코드의 복잡도가 떨어집니다. 이번에 처음 react-query를 사용해보았는데 눈에 띄게 편리함을 느꼈습니다. 

> 전반적으로 어떤 부분을 상태관리를 하려고 했는지, 상태관리는 어디까지 프론트에서하는게 좋을지 고민을 해보면 좋을 것 같아요. 이 부분에 대해서 코멘트 남겨주시면 더 좋을 것 같구요!

저는 클라이언트의 데이터를 믿지 않습니다. 충분히 바뀔 수 있기 때문이에요. 서버로부터 오는 데이터가 더 신뢰성이 높다고 생각합니다. 그래서 이번 미션을 진행하며  서버가 보내주는 데이터는 전역적으로 관리하지 않고 그대로 사용할 수 있도록 하였습니다. 프론트가 가지고 있어야하는 상태는 여러 컴포넌트에서 공통적으로 사용되며, 서버에서는 보내주지 않는 정보라고 생각합니다. 그런의미로 선택된 상품역시 서버에서 관리하면 더 데이터의 신뢰성이 높지않았을까하는 아쉬움이있습니다.

> hook에서 useQuery를 사용해서 API통신을 하고 있는데, 추상화가 가능할 것 같아요. 거의 형태가 비슷하고, 요청 url, queryKey만 다른것같아서요!

저도 동의합니다. 다만 이번에는 시간관계상 추상화를 진행하지 못했습니다.ㅠㅠ

2023-06-10 18:27 UTC, devhyun637 commented on src/components/common/header/Header.tsx
>            <Text color="#FFFFFF" size="largest" weight="bold" lineHeight="58px">
1번에 대해서는 다른 UI 라이브러리를 참고해보면 좋을 것 같아요~

> HTML <p> 요소는 하나의 문단을 나타냅니다. 시각적인 매체에서, 문단은 보통 인접 블록과의 여백과 첫 줄의 들여쓰기로 구분하지만, HTML에서 문단은 이미지나 입력 폼 등 서로 관련있는 콘텐츠 무엇이나 될 수 있습니다.

또` p`가 전체를 아우르는지에 대해서도 고민해보면 좋을 것 같구요. 스타일이 `block` 요소인 것을 포함해서요~

다른 UI 라이브러리에서의 `<Text>`, `<Typography>` 예시👇
https://www.material-tailwind.com/docs/react/typography
https://chakra-ui.com/docs/components/text/usage
https://nextui.org/docs/components/text

2023-06-10 18:38 UTC, devhyun637 commented on src/types/types.ts
앗.. 각각의 프로퍼티의 주석을 의미한거였습니다..!

2023-06-10 18:51 UTC, devhyun637 approved these changes
안녕하세요 루루~ 마지막 미션을 마무리할때가 되었군요 👏👏
질문드린 내용이 어려웠을 수도 있는데 상태관리에 대해서 많이 고민하고 생각을 한 것 같아서 좋네용~!

추가적인 피드백을 2개정도 남겨두었는데 시간날 때 가볍게 확인해보고, 에러핸들링 부분은 제가 공식문서 링크를 남겨드렸는데 어떤식으로 적용을 하셨는지 남겨주시면 좋을 것 같아용! 아직 제가 보기에는 서버 요청/응답에 대한 에러핸들링 부분이 아쉬워요 ㅠ.ㅠ

마지막으로 에디와 같이 페어를 하셨다니, 리액트쿼리를 사용한 것에 대해서 같이 보시면 좋을 것 같은 저의 의견 [링크](https://github.com/woowacourse/react-shopping-cart/pull/238#pullrequestreview-1473467695) 남깁니다! 

그럼 방학 즐겁게 보내시고 남은 우테코 기간도 화이팅하길 바라요!!
그동안 고생 많으셨습니다~

2023-06-10 18:51 UTC, merged