[장바구니 협업 step2] 제레미(김민석) 미션 제출합니다.
woowacourse/react-shopping-cart-prod pull request #127
Opened 2023-06-02 08:41 UTC by shackstack

[💍 배포 링크](https://shackstack-tiffany.vercel.app/)

작성예정

2023-06-03 00:35 UTC, lsw1164 requested changes
제레미, 코드 잘봤습니다.  
가독성이 좋았어요👍

에러 처리는 잘해주셨는데요.  
상품 목록 가져오는 요청에 실패한 경우라면 그냥 404 페이지를 바로 보여주기 보다는
사용자에게 재요청 가이드를 해도 좋을 거 같아요.

나머지는 코멘트 확인해주세요!

2023-06-03 00:35 UTC, lsw1164 commented on src/types/responseData.ts
> +  orderId: number;
Order의 타입이니까 요소들의 이름에 'order'라는 단어는 생략할 수 있어요.
orderId -> id
간결하게 표현할 수 있겠군요.

2023-06-03 00:35 UTC, lsw1164 commented on src/types/global.ts
> +};
src/types/global.ts 파일 이름에 따르면, 이 파일은 전반적인 타입들을 담고 있는 것처럼 보이네요.   
그러나, Select 타입을 보면 의미가 모호하고 전역 타입이 아닌 거 같아요.  
그냥 Select 타입은 아닌 거 같아요. order 요소도 포함하고 있군요.  

유저가 선택할 요소들이 앞으로 추가되면 혼동의 여지가 있습니다.

2023-06-03 00:35 UTC, lsw1164 commented on src/util/fetchList.ts
fetchList는 어떤 기능이죠? list만 받아올 거 같은 느낌을 받았어요.  
막상 로직을 보면 일반적인 get 요청으로 json 데이터를 가져오는군요.

2023-06-03 00:35 UTC, lsw1164 commented on src/hooks/useFetch.ts
> +      return JSON.parse(data);
json 데이터를 받아올 의도라면 [Response.json](https://developer.mozilla.org/en-US/docs/Web/API/Response/json)으로 해도 되지 않을까요?

2023-06-03 00:35 UTC, lsw1164 commented on src/hooks/useFetch.ts
> +export type FetchMethod = 'GET' | 'POST' | 'PATCH' | 'DELETE';
해당 타입이 중복 존재하는군요.

2023-06-03 00:35 UTC, lsw1164 commented on src/hooks/useFetchOrder.ts
> +      if (error instanceof Error) alert(error.message);
전반적으로 hook에 alert가 보이네요.  

alert는 UI 요소에요.  
hook 내부에서 UI 로직을 제어하면 장단점이 무엇일까요? 
고민해봅시다🤔 

+Error 객체에 포함된 메세지를 아무런 가공 없이 사용자에게 그대로 보여주는 걸까요?

2023-06-03 00:35 UTC, lsw1164 commented on src/hooks/useFetchCart.ts
비동기 요소인데 await를 사용하지 않은 부분들이 보이네요. 
이런 경우 try/catch는 어떻게 동작할까요? 🤔

2023-06-03 00:35 UTC, lsw1164 commented on src/components/Bill/Bill.tsx
주문 에러가 발생하고 있어요.  
에러는 발생할 수 있는데 처리 방법을 개선해봅시다.  
유저에게 500이라는 코드를 보여줄 필요는 없다고 생각해요.  

![error_display](https://github.com/woowacourse/react-shopping-cart-prod/assets/39941911/b6b9d60a-9f35-4478-a5b4-520033e2f33a)

2023-06-03 00:35 UTC, lsw1164 commented on src/store/path.ts
> +  ORDER_DETAIL_PAGE: '/detail',
ORDER_DETAIL_PAGE 값을 `detail`이라 하셨는데요. 
실제로는 `/orders/detail`이 아닐까요?
`detail`만으로는 order detail 페이지의 경로를 의미하지 않아요.

2023-06-03 00:35 UTC, lsw1164 commented on src/pages/OrderListPage.tsx
> +        {Array.from(orders).map((order) => {
orders의 타입이 배열이었다면
Array.from 없이 map을 바로 써도 됐을 거 같아요.

2023-06-03 02:51 UTC, shackstack commented on src/store/path.ts
> +  ORDER_DETAIL_PAGE: '/detail',
네 실제로는 '/orders/detail'이고 router에서
```
        {
          path: `${PATH.ORDER_LIST_PAGE}${PATH.ORDER_DETAIL_PAGE}/:id`,
          element: <OrderDetailPage />,
        }
```
이런 형태로 사용했습니다. 
서브라우터에 대한 path를 각각 작성하면 안정성이 떨어질 수 있다고 생각해서요.

말씀주신 것처럼  `ORDER_DETAIL_PAGE: '/detail'`는 네이밍에도 문제가 있고 계층구조도 잘못된 것 같습니다. 
수정하도록하겠습니다!

2023-06-03 03:28 UTC, shackstack commented on src/hooks/useFetch.ts
> +export type FetchMethod = 'GET' | 'POST' | 'PATCH' | 'DELETE';
헉... 수정하겠슴돠

2023-06-03 03:37 UTC, shackstack commented on src/util/fetchList.ts
현재 asyncSelector.ts파일에서 비동기 셀렉터로 상품목록, 장바구니 목록, 주문목록을 가져오고있습니다. 그래서 fetchList라는 이름으로 유틸함수를 분리하였습니다.

2023-06-04 04:44 UTC, shackstack commented on src/components/Bill/Bill.tsx
맞습니다... 쿠팡, 마켓컬리 레퍼런스를 참고해서  '요청을 처리할 수 없습니다'라는 메세지를 띄우도록 수정하였습니다!

2023-06-04 06:42 UTC, shackstack commented on src/types/global.ts
> +};
말씀주신것 처럼 이 타입은 cart.ts파일에서만 사용되고 있습니다. cart.ts로 타입을 옮기고 global.ts는 삭제하는 방향으로 수정해보겠습니다. 그리고 order가 추가되면서 Select라는 네이밍이 부적절하게 되었습니다. SelectedItem으로 수정해보겠습니다.

2023-06-04 07:10 UTC, shackstack commented on src/hooks/useFetchOrder.ts
> +      if (error instanceof Error) alert(error.message);
hook에서 UI로직을 처리하게 되었을 때 장단점이라 한다면....
장점으로는 에러메세지를 일괄적으로 보내줄 경우 hook에서 한번에 처리해줄 수 있어 효율성 측면에서의 이점이 있을 것 같고,
단점으로는 관심사의 분리가 제대로 이루어지지 않는다는 점이 있을 것 같습니다.

2023-06-04 07:13 UTC, shackstack commented on src/hooks/useFetchOrder.ts
> +      if (error instanceof Error) alert(error.message);
Error객체에 포함된 메세지가 '주문 요청에 실패했습니다'와 같은 구체적인 메세지로 오면 가공없이 그대로 보여줘도 될 것 같은데, 아직 에러메세지를 어떻게 구성할 것인지에 대한 이야기를 나눠보지 않아 우선 프론트딴에서 처리를 해야할 것 같습니다. 이 코드는 수정하도록하겠습니다!

2023-06-04 19:18 UTC, shackstack commented on src/hooks/useFetchCart.ts
fetch작업이 완료되지 않은채로 아래코드가 실행되겠군요...

2023-06-05 15:07 UTC, lsw1164 commented on src/hooks/useFetchCart.ts
예외가 발생할 때 catch도 안되겠죠?😅

2023-06-05 15:30 UTC, shackstack commented on src/hooks/useFetch.ts
> +      return JSON.parse(data);
```      
const data = await response.text();
if (!data) return null;
return await response.json();
```

말씀주신대로 이렇게 수정해보았는데 `TypeError: Failed to execute 'json' on 'Response': body stream already read` 이러한 오류가 발생해서 다시 원상복귀시켰습니다...

2023-06-05 15:32 UTC, shackstack commented on src/types/responseData.ts
> +  orderId: number;
response를 저 형식으로 받아와서 orderId로 작성하였습니다...!

2023-06-06 12:27 UTC, lsw1164 approved these changes
제레미, 레벨2까지 미션 고생 많으셨습니다. 

### 고민해보기 

- 관심사 분리
  - 웹 요청 레이어 고민해보기
  - 비즈니스 로직과 UI 로직 분리도 고민해보기

- 오류 상황 처리 
  - 오류 알림 대상이 누구인가? 유저? 동료 개발자?
  - 유저에게 알려둘 메세지와 개발자에게 알려줄 메세지 구분하기 
  - 오류 상황에서 유저에게 어떻게 안내해야 거부감을 최소화 할 수 있을지?

로그인 코드는 작성해주신 거 같은데 동작을 직접 확인하지 못해서 아쉽네요😅 
미션은 여기서 merge 하겠습니다. 코멘트에서 대화 이어갈 수 있어요.

2023-06-06 12:27 UTC, lsw1164 commented on src/hooks/useFetch.ts
> +      return JSON.parse(data);
response.text를 호출하고 response.json을 또 호출하셨군요.  
body로 넘어온 stream을 response.text로 끝까지 읽어서 더 이상 읽을 게 없는데 response.json으로 또 읽고 있어요.  
에러 메세지를 읽어보고 왜 그런지 분석하는 것도 정말 중요한 요소입니다!  
이번 기회에 stream이 뭔지? 에러가 왜 발생하는 지? 정리해보는 것도 좋겠군요.  

미션이 끝나더라도 꼭 알고 넘어가야 해요!

2023-06-06 12:27 UTC, lsw1164 commented on src/store/asyncSelector.ts
api 요청 수를 최적화 하신 거 같군요.  
recoil selector의 caching 정책을 파악하고 의도하신 걸까요? 👀

2023-06-06 12:27 UTC, lsw1164 commented on src/hooks/useFetchOrder.ts
> +      if (error instanceof Error) alert(error.message);
이번엔 hook에서 UI 로직까지 일괄처리 하도록 구현했다면 
다음 미션에서는 비즈니스 로직과 UI 로직의 관심사 분리를 신경써서 나눠보면 좋을 거 같아요.  

필요한 상황에서 적용할 수 있도록 여러 방법에 대해 직접 경험해보는 것도 중요하다고 생각해요.

2023-06-06 12:27 UTC, lsw1164 commented on src/components/Bill/Bill.tsx
`요청을 처리할 수 없습니다`는 메세지만 툭 주면 UX에 좋지 않을 거 같아요.  

어떤 메세지로 가이드 해야 유저가 에러를 마주해도 덜 불편한 상황일까요?  
고민해보면 좋겠습니다.

2023-06-06 12:27 UTC, lsw1164 commented on src/store/bill.ts
1. 전역으로 둔 상태는 어떤 기준으로 채택한 것인지?  
2. 반드시 전역이 아니어도 됐던 상태는 없었는지?  

고민해보면 좋을 거 같아요.

2023-06-06 12:27 UTC, lsw1164 commented on src/hooks/useSignIn.ts
> +  };
이런 방식은 신박하네요😮  
hook 내부에서 id, pw의 입력값이 바뀌는 걸 관리 하는 건가요?  
필요했던 기능일까? 라는 생각도 들었습니다.

2023-06-06 12:27 UTC, lsw1164 commented on src/util/fetchList.ts
fetchList라는 이름이 전달할 수 있는 의도와 로직이 매칭이 안되고 있어요😅  
사용처를 보니까 무조건 List를 받아올 때 쓰는 것도 아니고 객체 형태를 받아올 때도 사용하고 있더라고요.  

누군가는 알아서 잘 파악해서 사용하겠지만, 처음 읽는 사람은 혼란스러울 거 같아요.

2023-06-06 12:28 UTC, merged