[장바구니 협업 step2] 애슐리(허서영) 미션 제출합니다.
woowacourse/react-shopping-cart-prod pull request #131
Opened 2023-06-04 11:33 UTC by ashleysyheo

작성중...

2023-06-05 03:35 UTC, ashleysyheo commented
기존에 주문 목록 요청 `GET /orders`를 보냈을 때 `orderedItems` 내부에 `product` 객체를 보내줬었습니다. 이 객체가 상품 목록 조회할 때 응답받던 product 값과 같았고요! 그래서 `orderedItems`의 `product`의 `id`가 `productId`를 가리킨다고 생각해서 주문 상세 페이지에서 이 id를 기준으로 상품을 다시 장바구니에 담을 수 있는 기능을 넣으려고 했습니다. 그런데 알고 보니까 아예 다른 `id`여서 추가 커밋에서 이 기능만 삭제했습니다!

2023-06-06 16:48 UTC, pocojang requested changes
@ashleysyheo 반갑습니다!!
![unnamed](https://github.com/woowacourse/react-shopping-cart-prod/assets/23068523/979a3dcf-6813-4103-a5a2-20d86af999f6)


Step2만 봤는데도..  코드량이 어마어마하게 많아서.. 정말 놀랐습니다.
코멘트 리뷰는 따로 봐주세요!

## 피드백

### 1. null vs undefined

`null`을 상당히 많이 쓰시는데 `null` 때문에 생기는 핸들링 코드가 계속 발생되서 그 비용이 아깝다는 생각이 들어요. 혹시 어떠한 이유인지 궁금하네요

### 2. Recoil

상당히 잘 쓰고 있어요!
정말 범용적으로 잘 쓰이고 있는데 여기서 `Hooks`, `Domain` 계층이 컴포넌트에서 마치 `Recoil`이 뭔지 모르게 하도록 돕는 역할을 하고 있는 것 같네요.
잘 하셨습니다.

다만 `Hooks`, `Domain`의 역할이 좀 애매한 것 같아요.
보다보면 `Domain` 계층은 아예 제거되도 괜찮지 않을ㄲㅏ? 싶기도 하네요

### 3. 에러를 던지는 곳, 받는 곳

에러는 어디서 던지고 어디서 받아야할까요?
확실히 정리해보시는게 좋겠어요.
우리가 만든 장바구니 프론트엔드 앱에서는 에러를 어디서 던지고 어디서 받는지 말이죠.
또 비동기는 어디서 처리할지 말이죠..
혼동이 되어 정리하면 좋겠습니다.

### 4. async & await

`Promise` 객체를 다루는 모든 함수에 `async & await`를 모조리 때려넣는 느낌의 코드였어요.
혹시 의도되었다면 죄송하지만 차이를 아시는지 궁금했어요.
비동기 함수를 다룰때 `no async & no await`, `async & await`, `async & return await`, `promise().then().catch()` 이 모두의 차이점은 어떻게 될까요?
기준점이 명확하지 않게 느껴지기도 하고요. 모든 코드가 `async & await` 떡칠이 되고 있으니 꼭 알아보세요.
또한 이제는 [Top-level await](https://github.com/tc39/proposal-top-level-await)라는 것이 나왔는데 이게 왜 나왔을까?? 무엇이 불편하기에 나온 문법일까 고민해보시면 어느정도 해답이 될 것 같습니다.

### 5. mutation

이건 `TanStack Query`를 따라하신걸까요?
사실 왜 필요한건지는 잘 모르겠네요..
애초에 `mutation` 이름이 어울리지 않는 것 같습니다.
`TanStack Query`의 `mutation`이 사랑받는 이유는 `optimistic update` 때문이거든요.

현재 할 수 있는 기능만 봤을때는 `loadWithFetch`, `loadWithSetFetchData`와 같은 네이밍이 어울리지 않을까요?

또한 `finally()`를 추가해서 더 풍요롭게 고쳐보시면 좋겠네요!

### 6. export vs export default

`export default`를 사용해도 되는데 굳이 사용하지 않는 경우가 보이네요!
의도된 것이라면 할 말이 없긴한데..
어차피 단 하나의 모듈만 내보내는데도 `import { someModule } from 'someModule'` 이렇게 써야할 이유가 있을까요?

### 7. Date 다루기

`Date`를 다루는데 number 타입, string 타입 아주 많은 형변환이 오가고 있어 약간은 불안하네요.
요건 잘 정리해보시면 좋겠습니다.

### 8. 가격

가격을 다루는데 헛점이 좀 많은 것 같아요.
시간되신다면~~ 찾아보세요!

## 고민

### 에러 처리

정답은 아니지만 그래도 정말 의미있는 고민하셨네요!
훌륭합니다!
사실 1번과 2번.. 비교 대상이 좀 아이러니한 것 같아서 다른 비교대상을 고민해보셨으면 좋겠어요 ㅎㅎ
에러를 사용자에게 어떻게 표출할 것인가, 에러를 어디서 처리할 것인가 요게 더 중요하답니다.

### 프론트에서 처리할 데이터 vs 백에서 처리할 데이터 ?

프론트 개발자의 진가는 여기서나오는게 아닐까요?

1. 사용자에게 좋은 사용성을 제공
2. 철저한 유효성 검증
3. 서버 트래픽 절약

위의 3가지를 잘 지켜주시면 됩니다.

결론적으로 프론트에서 하는 일이 많으면 서버의 비용을 아끼지만 사용자의 성능을 갉아먹습니다. 그렇다면 그 반대는 어떨까요 ㅎㅎ 잘 생각해보세요.
유효성 검사는 프론트, 백엔드 모두 다 이중으로 체크해주는게 당연히 옳지 않을까요?
마지막으로 민감한 정보를 프론트에서 계산하고 그걸 백엔드에 넘기는건 정말 위험한 행위입니다.

궁금하시면 다양한 서비스를 직접 사용해보시고 자주 통신하는 코드는 인스타 좋아요 기능과 같은 사례를 찾아보세요

---

아 그리고 앱을 직접 만져봤는데.. 오우 엄청난데요?
사용성도 좋고 디자인도 정말 너무 이뻐서 굳이 코드 리뷰가 필요한가? 했답니다.
이번 미션에 많은 시간 갈아넣으셨을 것 같은데 훌륭합니다!

2023-06-06 16:48 UTC, pocojang commented on cypress/fixtures/productData.json
> +    "imageUrl": "https://cdn-mart.baemin.com/sellergoods/list/cba783a5-b35d-4b9d-b58e-56801594351f.jpg?h=400&w=400"
`mock data`라고 해도 `?h=400&w=400`와 같은 쿼리가 하드코딩 되어 있을 이유가 있을까요?

2023-06-06 16:48 UTC, pocojang commented on cypress/fixtures/productData.json
> +    "discountedPrice": 61100,
둘 중 하나는 없어야하는거 아닐까요..?

2023-06-06 16:48 UTC, pocojang commented on src/api/memberAPI.ts
> +    return await fetchAPI(`${baseUrl}${API_ENDPOINT.MEMBER}`, {
`async` & `await`를 여기서 해주면 어떤 효과가 있는걸까요?

2023-06-06 16:48 UTC, pocojang commented on src/api/memberAPI.ts
> +    return await fetchAPI(`${baseUrl}${API_ENDPOINT.MEMBER}`, {
`baseUrl + API_ENDPOINT.MEMBER` 사이에 `/` 슬래시가 없으면 앞으로 뒤에 붙는 API URL 규칙들도 헷갈리지 않을까요?

2023-06-06 16:48 UTC, pocojang commented on src/api/orderAPI.ts
> +import { OrderCartItemsData } from '../types/order';
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export

2023-06-06 16:48 UTC, pocojang commented on src/components/cart/CartCheckoutBox/CartCheckoutBox.styles.ts
>    CheckoutTotalPriceValueText,
잘못된건 아닌데요.
너무 도메인 가득한 네이밍으로 컴포넌트를 작성하셔서 어떤 `Element`인지 도저히 유추가 되지 않네요.
어떤 `Attribute`를 가졌고 어떻게 확장해야하는지 너무 강력하게 추상화되어 블랙박스 같습니다

2023-06-06 16:48 UTC, pocojang commented on src/components/cart/CartCheckoutBox/CartCheckoutBox.tsx
> +              : priceFormatter(-cartListCheckoutCosts.contents.totalMemberDiscountAmount)}
양수는 음수로.. 양수는 음수로..? 맞나요?

2023-06-06 16:48 UTC, pocojang commented on src/components/common/ServerSelect/ServerSelect.tsx
> +        onChange?.();
엄청 괴랄한 코드구나... 이게 뭐지 했는데 요구사항을 보고 이해했습니다.
요구사항을 위해 이런 선택을 하셨군요!
좋습니다!

2023-06-06 16:48 UTC, pocojang commented on src/components/order/OrderItem/OrderItem.tsx
> +          alt={information.orderedItems[0].name}
`information.orderedItems[0]`은 무엇을 의미할까요?

2023-06-06 16:48 UTC, pocojang commented on src/components/orderDetail/OrderDetailItem/OrderDetailItem.tsx
> +    <>
`Fragment`는 왜 쓰일까요?

2023-06-06 16:48 UTC, pocojang commented on src/components/orderDetail/OrderDetailPurchaseInformation/OrderDetailPurchaseInformation.tsx
> +    });
에러를 던지는 것은 좋은데요.. 어디서 잡아줄지 예상하고 던지시는게 맞을까요?

2023-06-06 16:48 UTC, pocojang commented on src/constants/api.ts
> +  [SERVER[3]]: process.env.REACT_APP_JM_API_BASE_URL,
`0,1,2,3` 또한 상수를 이용하여 네이밍을 잘 넣는게 어떨까요..?
뭔가 무지개마냥 외워야할가요?

2023-06-06 16:48 UTC, pocojang commented on src/constants/api.ts
>  } as const;
좋은 시도입니다 👍

2023-06-06 16:48 UTC, pocojang commented on src/constants/member.ts
> +
위에서 만든 `MEMBER_RANK`를 재활용 할 수는 없을까요?

2023-06-06 16:48 UTC, pocojang commented on src/constants/ui.ts
> +    value: (information: OrderData) => {
`LABEL`은 대문자이고 `value`는 소문자이라 어색한데.. 어떠세요?

2023-06-06 16:48 UTC, pocojang commented on src/domain/member.ts
> +    id: Number(new Date()),
무엇을 의도하는 코드일까요?

2023-06-06 16:48 UTC, pocojang commented on src/domain/member.ts
> +const seMemberData = (newMemberInformation: MemberInformation) => {
설마 오타..?!

2023-06-06 16:48 UTC, pocojang commented on src/domain/member.ts
> +    (foundRank: MemberRank | null, [memberRank, purchaseCondition], index): MemberRank | null => {
`| null`은 의도된걸까요?

2023-06-06 16:48 UTC, pocojang commented on src/domain/member.ts
> +    : { ...memberInformation };
코드 라인 수를 위한 집착이실까요..?

2023-06-06 16:48 UTC, pocojang commented on src/domain/member.ts
> +    null
`reduce` 초기값이 `null`인 경우는 잘 검증된걸까요?

2023-06-06 16:48 UTC, pocojang commented on src/domain/order.ts
> +    return orderedItem;
```suggestion
    return {
      quantity: cartItemData.quantity,
      ...cartItemData.product,
    };
```

2023-06-06 16:48 UTC, pocojang commented on src/domain/order.ts
> +      ...cartItemData.product,
`quantity`를 먼저 초기화하는 순서가 의도하신게 맞을까요?

2023-06-06 16:48 UTC, pocojang commented on src/domain/order.ts
> +const getOrderedItems = (cartItemIds: number[]): OrderedItemData[] => {
`cartItemIds: number[]`보다 더 정교한 타입을 사용하시는게 어떨까요?

2023-06-06 16:48 UTC, pocojang commented on src/hooks/common/useScrollToTop.ts
> +    window.scrollTo(0, 0);
`behavior: "smooth"` 정도는.. 어때요?

2023-06-06 16:48 UTC, pocojang commented on tsconfig.json
> +    "target": "esnext",
Nice 👍

2023-06-06 16:48 UTC, pocojang commented on src/utils/validator.ts
> +const areObjectsEqual = <T extends Record<string, unknown>>(obj1: T, obj2: T): boolean => {
`is` vs `are`

2023-06-06 16:48 UTC, pocojang commented on src/utils/formatter.ts
> +};
[Intl](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat)만 잘 사용하셔도 필요없는 코드랍니다

2023-06-06 16:48 UTC, pocojang commented on src/store/order.ts
> +      return orderItem ?? null;
`undefined`로 반환되는 것을 막기 위함일까요?
그렇다면 어떤 이득이 있는걸까요?

2023-06-06 16:48 UTC, pocojang commented on src/pages/OrderPage/OrderPage.tsx
> +      </Suspense>
오우 좋은데요?

2023-06-06 16:48 UTC, pocojang commented on src/pages/OrderPage/OrderPage.tsx
> +  useScrollToTop();
이 코드는 왜 필요할까요..?
혹시 스크롤 문제때문에 반창고마냥 패치한 코드는 아니겠죠?!

2023-06-06 16:48 UTC, pocojang commented on src/utils/formatter.ts
> +const dateFormatter = (createdAt: Date) => {
사용법이 상당히 특이하네요..
함수 네이밍과 구현부를 봐도 무슨 의미인지 이해가 안가서 한참.. 봤답니다

2023-06-06 16:48 UTC, pocojang commented on src/utils/formatter.ts
> +};
`createdAt` 타입은 `Date` 타입인데 `new Date()`에 한번 더 넣어주는건 어떤 효과가 있는지 궁금합니다

2023-06-06 16:48 UTC, pocojang commented on src/utils/costs.ts
> +    const discountRate = 'product' in curr ? curr.product.discountRate : curr.discountRate;
`in`을 사용하는게 올바른 사용 같지는 않군요..?

2023-06-06 16:48 UTC, pocojang commented on src/hooks/useCartCheckbox.ts
> +          return isAllChecked ? new Set([]) : new Set([...cartIdList]);
`new Set([...cartIdList]);`으로 매번 사용하시는데 `new Set(cartIdList);`이렇게 사용하는 것과 어떤 차이가 있는지 궁금합니다!

2023-06-06 16:48 UTC, pocojang commented on src/hooks/useCart.ts
> +            navigate(`${PATH.ORDER_SUCCESS}?orderId=${orderId}`);
이런 코드는 굉장히 많은 실수를 유발합니다
어떻게 사용하는게 좋을까요?

2023-06-06 16:48 UTC, pocojang commented on src/hooks/useCart.ts
> +        await Promise.all(cartItemIds.map((cartItemId) => cartAPI.deleteCartItem(cartItemId)));
오우 굿 좋습니다
다만.. 백엔드에서 API로 다건 처리를 해주시면 좋겠네요

2023-06-06 16:48 UTC, pocojang commented on src/domain/order.ts
> +  return [...orderList, order];
```suggestion
  const newOrder = {
    id: Number(new Date()),
    orderedItems,
    orderedAt: new Date(),
    ...serverOrderCosts,
  };

  return [...orderList, newOrder];
```

2023-06-06 16:48 UTC, pocojang commented on src/domain/order.ts
> +  const isValidOrder = areObjectsEqual(clientOrderCosts, serverOrderCosts);
`are-*`로 받고 `is-*`에 할당 🤔

2023-06-06 16:48 UTC, pocojang commented on src/domain/cart.ts
> +  });
이중 반복문을 어떻게 개선할 수 있을까 고민해보면 좋겠군요!

2023-06-06 16:48 UTC, pocojang commented on src/hooks/common/useToast.ts
> +  return { isAdded, setIsAdded };
컴포넌트에서 이런 네이밍으로 가져다쓰려면 헷갈리지 않을까요..?
차라리 `Tuple`형태로 내보내서 다시 이름을 바꿀 수 있다든가 `Toast`를 사용한다라는 것을 나타낼 수 있는 네이밍이면 좋겠군요!

2023-06-06 16:48 UTC, pocojang commented on src/hooks/common/useToast.ts
> +  const [isAdded, setIsAdded] = useState(false);
```suggestion
const useToast = (initIsAdd = false) => {
  const [isAdded, setIsAdded] = useState(initIsAdd);
```
이런 형태로 확장성을 열어둘 수 있지 않을까요?
아! 물론 일부러 숨기셨다면 그것도 괜찮네요 ㅎㅎ

2023-06-07 06:59 UTC, ashleysyheo commented on cypress/fixtures/productData.json
> +    "imageUrl": "https://cdn-mart.baemin.com/sellergoods/list/cba783a5-b35d-4b9d-b58e-56801594351f.jpg?h=400&w=400"
없습니다... ㅎㅎ 😅 배민 상회에서 별생각 없이 빠르게 그대로 가져온 것을 복붙하느라 추가되어 있었습니다. 하드코딩 된 값들은 제거했습니다!

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/fc9e011850ba1f5b3b360fa36465c70537bc1dba

2023-06-07 07:01 UTC, ashleysyheo commented on cypress/fixtures/productData.json
> +    "discountedPrice": 61100,
상품 목록에서 상품 할인이 있는 아이템을 보여줄 때 할인율이랑, 할인된 금액 모두 보여주고 있어서 둘 다 필요하다고 생각했습니다! 그리고 지금 백엔드에서 할인된 금액을 계산하는 방법이 상품을 추가할 때 할인율만 입력하면 할인된 금액을 자동을 계산해 주는 것으로 알고 있습니다. 

어떤 부분에서 둘 중 하나는 없어야 된다고 생각했는지 여쭤봐도 될까요?

2023-06-07 07:04 UTC, ashleysyheo commented on src/components/cart/CartCheckoutBox/CartCheckoutBox.tsx
> +              : priceFormatter(-cartListCheckoutCosts.contents.totalMemberDiscountAmount)}
지금 무조건 할인 차액은 양수로 들어오는 데, 사용자에게는 차액이기 때문에 `-`를 붙여서 보여주고 싶어서 위에처럼 작성했습니다. 그런데 포코가 말한 것처럼 나중에 명세가 바꿔서 양수가 아닌 음수로 들어오면 양수는 음수로, 음수는 양수로 보이는 상황이 발생할 수 있기 때문에 삼항 연산자로 0 이하일 때만 `-`를 붙이도록 변경했습니다.

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/1b10578c2d751d746504386ec0f32d8aab27d8d2

2023-06-07 07:05 UTC, ashleysyheo commented on src/components/orderDetail/OrderDetailItem/OrderDetailItem.tsx
> +    <>
그러게요...? 😅 수정했습니다!

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/b3866b71d5f7b473fa0df66554197a568212b647

2023-06-07 07:07 UTC, ashleysyheo commented on src/constants/api.ts
> +  [SERVER[3]]: process.env.REACT_APP_JM_API_BASE_URL,
기존 `SERVER` 상수를 배열에서 객체로 변경하고 그 값을 이용해서 더 명시적으로(?) 네이밍을 해보려고 했습니다!

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/290a57af70ef039e81237e9e878949ab519d1211

2023-06-07 07:08 UTC, ashleysyheo commented on src/constants/member.ts
> +
`MEMBER_RANK`를 기존 배열에서 객체로 변경한 다음에 그 값을 재활용 했습니다!

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/7b788cbaf1960d8b0acb8913b454607a15f37c3a

2023-06-07 07:09 UTC, ashleysyheo commented on src/domain/member.ts
> +const seMemberData = (newMemberInformation: MemberInformation) => {
😅 수정했습니다!

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/d272086b89ed2cc44ab44ac4f03be4107f149fdc

2023-06-07 07:11 UTC, ashleysyheo commented on src/domain/member.ts
> +    id: Number(new Date()),
백엔드에는 현재 멤버가 등록되어 있는 데, msw에서 모킹할 때, 제일 처음에는 멤버 데이터가 없기 때문에 새로운 멤버 데이터를 만들어서 추가해 주기 위한 코드입니다!

2023-06-07 07:14 UTC, ashleysyheo commented on src/domain/member.ts
> +    : { ...memberInformation };
코드 라인 수를 위한 집착이었던 것 같기도 하고요.... 🧐😅 개행 추가했습니다!

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/e3271c184a1b23fae4bc11f40773f6fa3c4b6fc0

2023-06-07 07:15 UTC, ashleysyheo commented on src/domain/order.ts
> +      ...cartItemData.product,
아니요...! 왜 그랬을까요? 하하... 전혀 의도하지 않았습니다. 

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/766d6b9b713235dc4f6c922ebcad38deeee25d61

2023-06-07 07:18 UTC, ashleysyheo commented on src/utils/validator.ts
> +const areObjectsEqual = <T extends Record<string, unknown>>(obj1: T, obj2: T): boolean => {
이 함수 네이밍 하는 거 정말 많이 고민했습니다... 아직도 잘 한 것인지 모르겠고요... `is`로 할지 `are`로 할지... 그런데 결론적으로 `areObjectsEqual`로 한 이유는 객체 두 개를 비교하는 것이기 때문에 복수로 하는 것이 맞지 않나 싶었습니다. 그런데 또 생각해 보면 뭔가 `is`로 시작하는 경우는 많아도 `are`로 시작한 경우는 또 거의 없는 것 같아서 뭐가 맞는지 정말 모르겠습니다. 🥲

포코는 어떻게 생각하시나요?

2023-06-07 07:23 UTC, ashleysyheo commented on src/utils/formatter.ts
> +};
`Intl.DateTimeFormat`라는 것이 있었군요! 몰랐습니다! 정말 편리하네요. 

`dateFormatter`랑 `timeFormatter` 둘 다 `Intl.DateTimeFormat`를 사용해봤습니다!

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/eaf8a5ee54725e50fc47f0907d49f1e1c2aa2573

2023-06-07 07:27 UTC, ashleysyheo commented on src/domain/order.ts
> +  const isValidOrder = areObjectsEqual(clientOrderCosts, serverOrderCosts);
이것 또한 고민이 많았습니다..... `areObjectsEqual`은 위에서 말했듯이 객체 두 개를 서로 비교하는 것이니까 `are-*`이 맞는다고 생각했습니다. 그런데 `isValidOrder`라고 한 이유는 `clientOrderCosts`가 `serverOrderCosts`랑 일치하기 때문에 니까, 주어(?)가 `clientOrderCosts`라고 생각해서 `is-*`를 사용했습니다.

많이 이상한가요...? 이럴 때는 어떻게 하는 게 좋나요? 정말로 모르겠습니다 🥲

2023-06-07 07:32 UTC, ashleysyheo commented on src/hooks/common/useToast.ts
> +  const [isAdded, setIsAdded] = useState(false);
일부로 숨겼습니다! Toast가 특성상(?) 처음부터 보이는 상황은 없다고 생각했기 때문입니다.

2023-06-07 07:35 UTC, ashleysyheo commented on src/hooks/common/useToast.ts
> +  return { isAdded, setIsAdded };
너무 당연하게 `isAdded`를 `Toast`랑 연관 지어서 생각하고 사용하고 있어서 그 부분에 대해서는 생각해 보지 못했네요! `isToastAdded`랑 `setIsToastAdded`로 변경해 봤습니다. 

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/464dbfd48a9be738f7273f6d8dd668b7c4c46e54

2023-06-07 07:39 UTC, ashleysyheo commented on src/components/order/OrderItem/OrderItem.tsx
> +          alt={information.orderedItems[0].name}
주문 목록에서 각 주문 내역을 표시할 때 가장 첫 번째 주문 아이템의 사진이랑 상품 명을 사용해서 보여주고자 해서 `information.orderedItems[0]`을 사용했습니다. 그런데 충분히 명시적이지 않은 것 같아서 위에서 `information.orderedItems[0]`을 `firstOrderItem`에 할당한 다음에 사용하도록 수정했습니다. 

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/2d8d60dcc1f8e3b7efb90950ee8ecc0000c263fb

2023-06-07 09:21 UTC, ashleysyheo commented on src/api/memberAPI.ts
> +    return await fetchAPI(`${baseUrl}${API_ENDPOINT.MEMBER}`, {
아무 효과도 없습니다...! 정말 생각 없이 코딩한 것 같네요 ㅎㅎㅎ 솔직히 말씀드리면 별생각 없이 비동기까 `async/await` 붙였습니다 😅

그런데 위 같은 상황에서는 `fetchAPI`가 이미 Promise를 반환하고 있고, 또 해당 프로미스를 기다린 후에 별도로 처리해야 하는 작업이 없기 때문에 굳이 `async/await`를 붙일 필요가 없습니다. 

나머지 부분들도 수정했습니다! 그런데 기존 `useMutationFetch`의 `mutationFn`으로 넘겨주는 함수에는 `async/await`를 그대로 뒀는데요, 그건 `useMutationFetch`에서 타입 처리를 어떻게 할지 모르겠어서입니다...

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/fad2973326887db01c1130cf98f1a5e1de68f32a

2023-06-07 09:24 UTC, ashleysyheo commented on src/utils/formatter.ts
> +};
없습니다. 왜 그랬을까요? 😅👀

그런데 이 부분은 제가 착각했습니다! 저는 `.json()`을 하면 날짜 데이터 값이 Date 타입으로 들어온다고 생각했는데 그냥 `string` 타입이더라고요. 그래서 `Intl.DateTimeFormat` 사용할 때 `.format()`에 `createdAt`을 넣으면 에러가 발생했습니다. 그래서 데이터 타입을 `string`으로 수정했습니다.

2023-06-07 09:25 UTC, ashleysyheo commented on src/utils/formatter.ts
> +const dateFormatter = (createdAt: Date) => {
`Intl.DateTimeFormat`을 사용하는 방향을 수정해 봤습니다!

2023-06-07 09:44 UTC, ashleysyheo commented on src/components/orderDetail/OrderDetailPurchaseInformation/OrderDetailPurchaseInformation.tsx
> +    });
렌더링 도중에 throw 한 에러이기 때문에 가장 가까운 에러 바운더리에서 잡는다고 이해하고 던졌습니다. 혹시 제가 잘 못 알고 있나요...?

2023-06-07 09:46 UTC, ashleysyheo commented on src/domain/cart.ts
> +  });
지금으로서 제가 생각할 수 있는 방법은 `filter` 안에서 `includes`를 사용해서 `cartItemIds`에서 `cartItem.id`를 포함하지 않는 것만 `!`를 붙여서 `true`값을 리턴해주는 것입니다. 

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/889fe3b8a6742e49ace682c7f1d883dffc2dec18

2023-06-07 09:50 UTC, ashleysyheo commented on src/pages/OrderPage/OrderPage.tsx
> +  useScrollToTop();
반창고마냥 패치한 코드가 맞기는 맞는데요......👀

그런데 그 코드가 없으면 다른 페이지에 스크롤을 왕창한 상태에서 주문 내역 페이지로 가면 스크롤 위치가 고정이지 않나요...? 이게 아닌가요....?

2023-06-07 10:06 UTC, ashleysyheo commented on src/api/orderAPI.ts
> +import { OrderCartItemsData } from '../types/order';
오... 이런 게 있었군요.... 알려줘서 감사합니다!!

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/f2c959c5dba5aa5b7682f862981d7a9da7f5b4cf, https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/02189979e7efe432f443bede4bc3b7ac82ac31dd

2023-06-07 10:10 UTC, ashleysyheo commented on src/api/memberAPI.ts
> +    return await fetchAPI(`${baseUrl}${API_ENDPOINT.MEMBER}`, {
이 부분에 대해서는 크게 생각해 본 적이 없었는데, 포코의 말처럼 헷갈릴 수도 있을 것 같습니다! 일관성을 위해서 붙여 주는 것이 좋겠네요

2023-06-07 12:51 UTC, ashleysyheo commented on src/components/cart/CartCheckoutBox/CartCheckoutBox.styles.ts
>    CheckoutTotalPriceValueText,
이번 장바구니 미션 하면서 처음 styled components를 사용해 보는데 정말 네이밍 하는 게 어렵더라고요.... 적으면서도 이게 맞나 싶기도 하고 뭔가 계속 엄청 길어지고.... 아직 어떻게 하는 것이 좋은 건지 잘 모르겠습니다!

그래도 리팩토링하면서 조금 더 제너럴(?) 하게 네이밍을 변경해 보려고 노력은 했습니다.

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/c8018afd755620ec77fbe2dccf283b1aef4b5a38

2023-06-07 12:55 UTC, ashleysyheo commented on src/constants/ui.ts
> +    value: (information: OrderData) => {
이 부분에 대해서도 고민이 정말 많았습니다... 대문자로 할지 소문자로 할지... 🫠
뭔가 메서드 명을 대문자로 하는 게 조금 어색해서 소문자로 적었는데 또 생각해 보면 `as const`를 추가해서 `readonly`로 설정했으니까 대문자로 하는 것이 말이 되는 것 같기도 하네요. 통일성을 주기 위해서 대문자로 변경했습니다!

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/e0bc9fe2eebdad8079926ed80d2ca41f6fe8c092

2023-06-07 12:58 UTC, ashleysyheo commented on src/domain/member.ts
> +    (foundRank: MemberRank | null, [memberRank, purchaseCondition], index): MemberRank | null => {
의도했습니다. 밑에 `if` 문에서 조건을 충족하지 못하면 `foundRank`값은 계속 `null`일 것이고 `newRank`는 `null` 값을 가지게 될 것입니다. 명시적으로 새로운 등급으로 승급하지 못했다는 것을 표현하기 위해서 `null`을 사용했습니다.

2023-06-07 13:04 UTC, ashleysyheo commented on src/domain/member.ts
> +    null
이 부분은 제가 잘 이해하지 못한 것 같습니다... 힌트를 주실 수 있을까요..?

`reduce`의 초깃값을 `null`로 준 이유는 밑에서 `return`할 때 `newRank`가 `null`인지 아닌지에 따라 등급을 업데이트할지 말지를 결정하기 위해서 그랬습니다.

2023-06-07 13:08 UTC, ashleysyheo commented on src/store/order.ts
> +      return orderItem ?? null;
`find`를 사용하면 찾고자 하는 것이 없으면 `undefined`를 리턴해서 그것을 사용해도 되겠지만, 이게 제가 의도한 undefined 인지 아닌지를 판별하기 어려울 때가 있어서 명시적으로 값이 없다는 것을 적기 위해서 `null`을 사용했습니다.

그런데 그러기 위해서 `null`을 사용했는데, 제가 제대로 `null` 체킹을 안 하고 있더라고요!? 그냥 `(!orderItem)`이런 식으로 `if`문안에서 검사하고 있길래 이 부분은 확실하게 `null`인지 검사하는 방법을 수정했습니다.

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/422f1ff6c8d0caefbd367012aa37fa4e58903d3d

2023-06-07 13:12 UTC, ashleysyheo commented on src/hooks/useCartCheckbox.ts
> +          return isAllChecked ? new Set([]) : new Set([...cartIdList]);
없습니다...... 심지어 두 군데서는 `new Set(cartIdList)`처럼 쓰고 다른 두 군데서는 `new Set([... cartIdList])`처럼 썼더라고요. 

정말 자잘한 실수가 많네요 하하하하....

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/68e318e30d5d7f57872c9cd833fee7efc98cc61d

2023-06-07 13:29 UTC, ashleysyheo commented on src/utils/costs.ts
> +    const discountRate = 'product' in curr ? curr.product.discountRate : curr.discountRate;
`in`을 사용하면 프로토타입 체인에 있는 속성들도 확인할 수 있어서 인가요...?

따로 type guard 유틸 함수를 만들어서 사용하는 방향으로 수정해 봤습니다!

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/0dbe46bb20ebf850332092dc6a4eec450bf9ec73

2023-06-07 13:33 UTC, ashleysyheo commented on src/hooks/common/useScrollToTop.ts
> +    window.scrollTo(0, 0);
넣을까 했거든요, 그런데 너무 멀미 나서 같아서 뺐습니다 😅 (저만 그런가요...?)

2023-06-08 05:25 UTC, ashleysyheo commented on src/hooks/useCart.ts
> +            navigate(`${PATH.ORDER_SUCCESS}?orderId=${orderId}`);
이 부분은 제가 잘 이해하지 못한 것 같습니다. 어떤 부분에서 많은 실수를 유발한다는 것인지 여쭤봐도 될까요...? 

혹시 `orderId={orderId}` 이렇게 적으면서 오타가 발생하는 부분을 말씀하시는 것일까요? 찾아보면서 `react-browser-router`에서  `createSearchParams`라는 것이 있더라고요. 이걸 사용해서 `useNavigateSearchParams`라는 커스텀 훅을 만들어서 쿼리 파람을 직접 안 적고 만드는 방식으로 변경해 봤습니다.

수정 커밋: https://github.com/woowacourse/react-shopping-cart-prod/pull/131/commits/3e72b7518c35d67145bd2ad503792ecac7f53c7f

2023-06-08 06:04 UTC, ashleysyheo commented
안녕하세요 포코! 

꼼꼼한 리뷰 감사합니다 🙇🏻‍♀️

내일이 미션 제출 마감이어서 아직 부족한 부분 많지만 리뷰 요청 보냅니다! 포코가 리뷰 남긴 부분들 중에서 모르겠거나 이해 안 되는 부분들은 커멘트에 답변으로 남겼습니다. 

#### null vs undefined
명시적으로 없다는 것을 표시하기 위해서 `null`을 사용했습니다. 제가 의도한 `undefined`인지 아니면 암묵적으로 발생한 `undefined`인지 구분하기 어려울 때가 있어서 사용했습니다. 

#### Recoil

`domain`은 `msw`에서 필요한 로직들을 분리한 것이었습니다! 그런데 이 로직들은 recoil에서도 재사용할 수 있을 것 같아서 사용했습니다. 

#### 에러를 던지는 곳, 받는 곳

이 부분은 제가 더 고민해보고 정리해 보겠습니다....!

#### async & await

조금 생각을 안 한 부분들이 있더라고요... 😅

> 또한 이제는 [Top-level await](https://github.com/tc39/proposal-top-level-await)라는 것이 나왔는데 이게 왜 나왔을까?? 무엇이 불편하기에 나온 문법일까 고민해보시면 어느정도 해답이 될 것 같습니다.

이건 처음 들어봤는데 더 알아보겠습니다!

#### mutation

> 이건 TanStack Query를 따라하신걸까요?

특별히 TanStack Query를 따라 한 것은 아닙니다! (사실 아직 TanStackQuery가 뭘 하는지 잘 알지도 못합니다...) 

원래는 recoil로 비동기 처리를 다 하고 싶었는데 `GET` 요청은 나름대로 하기 괜찮게 처리할 수 있었는데 `POST`, `PATCH`, `DELETE`는 처리하기게 애매하더라고요, 특히 에러처리가요. 그래서 커스텀 훅을 하나 만든 것입니다! 

이름은 그냥 `GET`이 아니고 데이터를 변경하는 메서드를 위해 사용되는 커스텀 훅이니까 mutation이라는 단어를 사용했습니다. (네이밍 정말 어려웠습니다...) 그런데 포코가 제안해 주신 네이밍이 더 어울리는 것 같아서 `useLoadWithSetFetchData`로 변경해 봤습니다.  

#### export vs export default

제 나름을 기준을 가지고 사용하려고 했습니다! 컴포넌트 같은 경우에는 export default를 사용하고 다른 것들은 export를 사용했습니다. 함수나 상수나 타입 같은 경우에는 정의한 이름 그 자체로 사용되는 것이 맞다고 생각했기 때문입니다. 

#### 확장성 없는 컴포넌트

이번에 styled components를 처음 사용해 봤는데 아직까지 좋은 점을 못 느끼겠습니다 🥲 뭔가 네이밍도 어렵고 아직까지는 충분히 css만으로도 할 수 있을 것 같고....

> 컴포넌트의 생김새를 묘사하는 컴포넌트 네이밍이 아니라 도메인이 그득그득 들어가있는 컴포넌트 네이밍으로 계층을 구조화하셨어요

질문이 있습니다! 보통은 styled components 네이밍 할 때 제너럴 하게 생김새 위주로 네이밍 하나요? 

이번에 리팩토링하면서 네이밍을 덜 도메인과 밀접하게 만들어보려고 했습니다. 그리고 `S.`를 붙이고 안 붙이는 기준은 재사용 가능한 컴포넌트로 만들어 뒀다면 `css` 스타일을 props로 넘겨서 사용할 수 있게 하고, 보통 html 태그를 스타일링 해야 된다면 `S.`를 붙여서 사용했습니다. 

확장성은... 아직까지는 common 빼고는 어떻게 컴포넌트들을 재사용할지 그림이 안 그려져서 어떻게 해야 할지 모르겠습니다. 🥲 

방학동안 열심히 더 공부해 보겠습니다!

감사합니다!

2023-06-09 00:44 UTC, pocojang commented on cypress/fixtures/productData.json
> +    "discountedPrice": 61100,
백엔드에서 그렇게 결정되었따면 어쩔 수 없겠네요 ㅎㅎ
저는 불필요한 중복 코드가 될 수 있다 생각했습니다~
할인율만으로도 프론트에서 로직 구성이 가능하니까요!

2023-06-09 00:45 UTC, pocojang commented on src/api/memberAPI.ts
> +    return await fetchAPI(`${baseUrl}${API_ENDPOINT.MEMBER}`, {
아하 그랬군요 ㅋㅋ
바쁘게 구현하다보면 충분히 그럴 수 있죠!

2023-06-09 00:46 UTC, pocojang commented on src/components/cart/CartCheckoutBox/CartCheckoutBox.styles.ts
>    CheckoutTotalPriceValueText,
아항..?
`CSS in JS`와 친해질 시간이 필요하셨군요 ㅎㅎ

2023-06-09 00:47 UTC, pocojang commented on src/components/orderDetail/OrderDetailPurchaseInformation/OrderDetailPurchaseInformation.tsx
> +    });
사실 이 부분에 정답이 있는건 아닙니다 ㅎㅎ

2023-06-09 01:02 UTC, pocojang commented on src/domain/member.ts
> +    null
값을 누적한다는 행위에 `null`을 다른 타입으로 누적한다는 것 자체가 위험해서 여쭤봤습니다 ㅎㅎ

2023-06-09 01:03 UTC, pocojang commented on src/hooks/common/useScrollToTop.ts
> +    window.scrollTo(0, 0);
ㅋㅋㅋ그렇게 느끼는 분도 있으시겠군요

2023-06-09 01:04 UTC, pocojang commented on src/utils/validator.ts
> +const areObjectsEqual = <T extends Record<string, unknown>>(obj1: T, obj2: T): boolean => {
음 이미 `is-` 플래그 변수에 할당하고 계셔서.. `is`가 더 좋은 방향 같긴합니당

2023-06-09 01:04 UTC, pocojang commented on src/pages/OrderPage/OrderPage.tsx
> +  useScrollToTop();
ㅋㅋ스크롤 문제로 골치 아프신가본데..
사실 렌더링 문제 아닐까요?!

2023-06-09 01:05 UTC, pocojang commented on src/utils/formatter.ts
> +};
ㅋㅋ광속의 코딩을 하시나보군요

2023-06-09 01:05 UTC, pocojang commented on src/utils/costs.ts
> +    const discountRate = 'product' in curr ? curr.product.discountRate : curr.discountRate;
`hasOwn`이 더 올바른 사례로 보입니다 ㅎㅎ

2023-06-09 01:06 UTC, pocojang commented on src/hooks/useCart.ts
> +            navigate(`${PATH.ORDER_SUCCESS}?orderId=${orderId}`);
정답입니다 💯

2023-06-09 01:06 UTC, pocojang commented on src/domain/order.ts
> +  const isValidOrder = areObjectsEqual(clientOrderCosts, serverOrderCosts);
쵸큼..이상하군요

2023-06-09 01:07 UTC, pocojang commented on src/hooks/common/useToast.ts
> +  const [isAdded, setIsAdded] = useState(false);
오홍 네네 좋습니다

2023-06-09 16:47 UTC, pocojang approved these changes
드디어! 레벨2 마지막 미션 마지막 리뷰네요~~

## Q&A

### Q. 보통은 styled components 네이밍 할 때 제너럴 하게 생김새 위주로 네이밍 하나요?

제너럴이 아니라 `Primitive`하게 하는게 좋다라는 것을 말씀드리고 싶습니다.
또한 절대 `styled`에 국한된 이야기도 아닙니다.
계속 반복되는 Radix UI, Rebass.. 들의 문서 예시를 잘 봐주세요

사물 즉 `요소(HTML Element)`를 `React Component`로 묘사할때 생김새 혹은 `시멘틱 요소`에 주목해주셨으면 좋겠습니다.
어려운 얘기죠.

문이라는 컴포넌트를 만들때 화장실 문, 우리집 문, 우테코 문으로 만들지말자. 일단 네모난 문이라는 컴포넌트를 만들고 그것을 조합하며 확장하자라는 이야기입니다.

---

엄청 빠르게 구현하면서 코드량도 상당히 많으니 얼마나 노력하셨는지 리뷰어로서 많은 것을 느낄 수 있었습니다.
코드도 잘 작성하시고 빠르게 배우는 능력도 있으시고 활용 능력도 좋으신 것 같아요.
`Styled`를 처음 다루셨다고 하셔서 놀랐습니다!

마지막으로..! 이미 충분히 잘하지만 나중에는 코드를 쉽게 작성하는 것도 고려해보시면 좋겠습니다.
잘하시는 것 같은데 코드를 굳이 어렵게 복잡하게 작성한다는 게 아닌가 느껴져요 💭 

우테코 정규 과정 정말 고생 많으셨습니다.
긴 휴식 기간에 이어 이제 정말 찐 프로젝트로 넘어가시는군요~~ 그럼 이만~~ 👋

2023-06-09 16:47 UTC, pocojang commented on src/hooks/common/useNavigateSearchParams.ts
정말 유틸 함수를 쏙쏙 잘 만드시는 것 같습니다

2023-06-09 16:47 UTC, pocojang commented on src/constants/api.ts
> +  [SERVER.JM]: process.env.REACT_APP_JM_API_BASE_URL,
<img width="476" alt="Screenshot 2023-06-10 at 12 57 41 AM" src="https://github.com/woowacourse/react-shopping-cart-prod/assets/23068523/c1faabff-93f5-4fc4-b55f-9ac84711a625">

2023-06-09 16:47 UTC, pocojang commented on src/types/member.ts
> +type MemberRank = (typeof MEMBER_RANK)[keyof typeof MEMBER_RANK];
이야.. 하나를 가르치면 열을..!!! 💯

2023-06-09 16:47 UTC, pocojang commented on src/domain/order.ts
> +    orderedAt: String(new Date()),
좋은 방법은 아니라서 나중에~~~ `ISO`, `Timestamp` 등에 대해 찾아보세용

2023-06-09 16:47 UTC, pocojang commented on src/domain/member.ts
> +        console.log(accumulatedPurchases, purchaseCondition, memberRank);
😱

2023-06-09 16:47 UTC, pocojang commented on src/domain/member.ts
> +    : { ...memberInformation };
그러고보니 `...`이 필요한가요..?

2023-06-09 16:47 UTC, pocojang commented on src/domain/member.ts
> +    : { ...memberInformation };
흠.... 조건문을 너무 어렵게 작성하시는 것 같아요
아래와 같이도 할 수 있지 않을까요?

```js
// Case 1
return {
  ...memberInformation,
  ...(newRank !== null && {
    rank: newRank,
    discountRate: MEMBER_DISCOUNT_RATE[newRank],
  })
}

// Case 2
if (newRank !== null) {
  memberInformation.rank = newRank;
  memberInformation.discountRate = MEMBER_DISCOUNT_RATE[newRank];
}

return memberInformation
```

2023-06-09 16:47 UTC, pocojang commented on src/domain/order.ts
> +    const cartItemData = currentCartData.find((cartItem) => cartItemId === cartItem.id)!;
뒤에 느낌표는 뭔가요..?

2023-06-09 16:47 UTC, merged