[장바구니 협업 Step 2] 룩소(우정균) 미션 제출합니다.
woowacourse/react-shopping-cart-prod pull request #170
Opened 2023-06-05 08:54 UTC by woo-jk

안녕하세요 케빈!! 드디어 케빈에게 리뷰를 받을 수 있겠네요 ㅠㅠ 만나서 반갑습니다!

장바구니 협업미션 step1부터 지금까지 정말 쉽지 않았는데요..

step1 코드 리팩토링에 시간을 많이 투자했는데요, 이 때문에 step2 미션을 늦게 부랴부랴해서 리팩토링을 하지못해 코드의 퀄리티가 많이 아쉬운 상태입니다.. ㅠ

이번 미션에서 중점을 둔 부분과 궁금했던 점들에 대해 정리하겠습니다!

# 중점을 둔 부분
### Suspense
step1의 코드를 리팩토링 하면서 이 Suspense 사용법과 활용에 대해 오랫동안 학습했습니다.

### 커스텀 훅

### 서버 변경

# 궁금한 점

2023-06-07 08:08 UTC, jeoongbin commented
유저 입장에서는 이렇게 컴포넌트가 뜰때 로딩이 나오는게 익숙치 않은 화면일텐데 수정해볼수있을까요?
https://github.com/woowacourse/react-shopping-cart-prod/assets/117629796/4976f3d4-fee9-47bd-8253-6462973040ff

2023-06-07 08:12 UTC, jeoongbin commented
삭제를 눌렀지만, 잠깐 장바구니에서 없어지지 않는 현상이 있는데 이건 어떻게 해결할수 있을까요?
https://github.com/woowacourse/react-shopping-cart-prod/assets/117629796/0061d084-9aca-44f6-b093-b09c66d223bc

2023-06-07 08:13 UTC, jeoongbin commented
번외로 (꼭 반영안해주셔도 됩니다.)
<img width="142" alt="image" src="https://github.com/woowacourse/react-shopping-cart-prod/assets/117629796/6e4fc54d-ad4f-4e00-8a57-b59a33edeb52">

유저에게 가장 좋은 혜택을 자동으로 선택해주면 어떨까요?

2023-06-07 08:41 UTC, jeoongbin requested changes
안녕하세요 룩소 :) 
처음 뵙겠습니다. 이번 미션 리뷰어를 맡게된 케빈입니다

전체적으로 깔끔했는데, 의도하신 부분인지는 모르겠지만, 로딩이 너무 강하게 들어가있더라구요!
사용자 경험을 위해서 넣어주신건 좋은데, 뭔가 계속해서 노출되서 오히려 불편함감이 조금 있었던거 같아요
나머지는 다 좋았습니다.

좀더 말씀드리고 싶은 부분 코멘트로 남겨두었습니다.
스텝2 하느라 고생많으셨습니다  :slightly_smiling_face:

2023-06-07 08:41 UTC, jeoongbin commented on README.md
> +>>>>>>> bbb5e8c3 (feat: add contents)
리드미가 좀 이상한데요??
충돌난채로 올라간거 같아요

2023-06-07 08:41 UTC, jeoongbin commented on src/components/cart/CartItem/CartItem.tsx
> +    uncheckCartItem(id);
네이밍에서 고통받으신게 느껴집니다

2023-06-07 08:41 UTC, jeoongbin commented on src/types/product.ts
> +export type CouponType = 'percent' | 'amount';
파일 내에서만 사용된다면 export 를 제거해주시는것도 좋을거같아요

2023-06-07 08:41 UTC, jeoongbin commented on src/components/cart/PaymentAmount/usePaymentAmount.ts
> +  const deliveryFee = checkedCartIdList.length ? 3000 : 0;
룩소만의 비지니스 로직이 있겠지만, 처음보는 사람입장에서 이해가 잘 되지 않아요.
체크된 카트 리스트가 없다면 0, 있다면 3000 맞을까요?
이런 로직이라면 추후 추가되는 비지니스 로직 (물건값이 15,000 원 이상일 경우 무료배송) 에 대해 대응하기 쉽지 않아 보이는데 다르게 수정해볼수 있을까요?

2023-06-07 08:41 UTC, jeoongbin commented on src/components/common/Header/Header.tsx
> +    navigate('/order');
경로는 자주 사용되서 변수로 두고 재사용 해보는건 어떨까요?

2023-06-07 08:41 UTC, jeoongbin commented on src/utils/ServerUrl.ts
> +    BASE_URL[serverName] + ORDERS_PATH_NAME,
```suggestion
const urlConfig = {
  getCartItemsUrl: (serverName: ServerName) =>
    `${BASE_URL[serverName]}${CART_ITEMS_PATH_NAME}`,

  getCouponsUrl: (serverName: ServerName) =>
    `${BASE_URL[serverName]}${COUPONS_PATH_NAME}`,

  getUsersCouponUrl: (serverName: ServerName) =>
    `${BASE_URL[serverName]}${USERS_COUPON_PATH_NAME}`,

  getOrdersUrl: (serverName: ServerName) =>
    `${BASE_URL[serverName]}${ORDERS_PATH_NAME}`,
};
```
이렇게 바꿔보면 어떨까요

2023-06-07 08:41 UTC, jeoongbin commented on src/types/server.ts
> +const serverNameList = ['누누', '체인저', '필립', 'Mock'] as const;
👍 
격리된 환경에서 테스트할수 있는거 좋은거 같아요

2023-06-07 08:41 UTC, jeoongbin commented on src/mocks/handlers.ts
> +  console.log('장바구니 검증 통과');
확인이 끝났으면 전체적으로 console.log 를 지워주시는게 좋아요

2023-06-07 08:41 UTC, jeoongbin commented on src/globalState/selectors/fetchCartItemList.ts
> +  },
의 용도는 무엇일까요?

2023-06-07 08:41 UTC, jeoongbin commented on src/components/cart/CartList/CartList.tsx
> +  useResetCartWhenServerChange();
이 부분은 useEffect 안에 들어가면 안되나요?

2023-06-07 08:41 UTC, jeoongbin commented on src/components/common/Modal/Modal.tsx
> +  };
모달을 만들다 보면 외부 클릭시 꺼짐 등의 기능을 구현하기 위해 모달 내부의 함수를 사용해야할때가 있는데, hook으로 빼서 모달을 쓰는곳에서도 닫힘을 사용할수있게 해보면 어떨까요?

2023-06-08 15:35 UTC, woo-jk commented on README.md
> +>>>>>>> bbb5e8c3 (feat: add contents)
헉.. 깃 문제로 인해서 이것 저것 수정하다가 그냥 올라간 것 같은데 실수로 못봤네요 ㅠㅠ 수정했습니다!

2023-06-08 15:36 UTC, woo-jk commented on src/components/cart/CartItem/CartItem.tsx
> +    uncheckCartItem(id);
넵 ㅠㅠ 네이밍은 아직도 고민 중입니다..

2023-06-08 15:37 UTC, woo-jk commented on src/types/product.ts
> +export type CouponType = 'percent' | 'amount';
삭제했습니다!

2023-06-08 16:41 UTC, woo-jk commented on src/components/cart/PaymentAmount/usePaymentAmount.ts
> +  const deliveryFee = checkedCartIdList.length ? 3000 : 0;
아직 배송비 관련 확실한 요구사항이 없어서 제가 임의로 물건이 있으면 3000원, 없으면 0원으로 설정했습니다!

일단은 deliveryFee를 변수 그 자체로 내보내는 것 보다는 getDeliveryFee()라는 함수를 사용하는 로직으로 변경을 했습니다만.. 
이게 확장성있게 바꾼건지는 잘 모르겠네요..  어떤 배송비 요구사항이 올지 모르니 어떻게 확장성 있게 변경할지 감이 잘 안옵니다 ㅠ 힌트라도 주실 수 있을까요!?

2023-06-08 16:50 UTC, woo-jk commented on src/components/common/Header/Header.tsx
> +    navigate('/order');
넵 경로 상수화 하겠습니다 감사합니다.

2023-06-08 16:58 UTC, woo-jk commented on src/utils/ServerUrl.ts
> +    BASE_URL[serverName] + ORDERS_PATH_NAME,
지금 보니 ServerUtil이라는 객체명이 엄청 애매했던 것 같네요.. urlConfig라는 네이밍이 조금 더 사용자 입장에서 이해하기 쉬울 것 같아요.

그리고 문자열 + 문자열 형식을 템플릿 리터럴로 적용시켰습니다!

2023-06-08 17:06 UTC, woo-jk commented on src/globalState/selectors/fetchCartItemList.ts
> +  },
selector의 캐싱을 최대 한 번만 허용하는 옵션입니다. 
리코일의 비동기 selector의 경우 한 번 호출하면 반환 값을 캐싱시켜서 다음 번 호출에서도 같은 값을 반환하더라구요.
fetchCartItemList의 경우 서버에서 계속해서 바뀌는 장바구니 아이템을 가져와야 하는데 selector에선 캐싱된 값을 계속 반환 해버리는 문제가 있었습니다.
이를 막기위해 저런 옵션을 넣었지만,, 어차피 refresh 함수로 캐시 제거 로직을 수행하니 필요없는 로직인 것 같아 제거하겠습니다.

2023-06-08 17:07 UTC, woo-jk commented on src/globalState/selectors/fetchCartItemList.ts
> +  },
위와 같은 캐시 문제 겪고나서 api fetch와 recoil은 서로 어울리지 않다는 점을 깨달았습니다..

2023-06-08 17:10 UTC, woo-jk commented on src/components/cart/CartList/CartList.tsx
> +  useResetCartWhenServerChange();
useResetCartWhenServerChange 훅을 useEffect에 넣으라는 말씀이실까요??
useResetCartWhenServerChange 훅 자체가 내부에서 useEffect를 사용하는 훅이기 때문에 외부의 useEffect에는 넣지 못할 것 같다고 생각합니다..!

2023-06-08 17:29 UTC, woo-jk commented on src/components/common/Modal/Modal.tsx
> +  };
모달 컴포넌트를 사용하는 사용처에서 따로 상태를 새로 정의하거나 할 필요 없이 <Modal/> 만 가져와서 붙이면 
알아서 작동 가능하도록 하고 싶어서 Modal 내부에 isOpen 상태를 뒀습니다. 사용처에선 trigger 프롭스를 통해 open 할 수 있도록 했습니다.

이 방식보단 케빈이 말씀하신 외부에서 modal 관련 훅을 사용해 상태나 open/close 함수를 가져온 뒤 모달을 작동시키는 방식이 더 나은 방식일까요? 
제가 생각하기엔 확실히 두 번째 방식은 기능의 확장성? 범용성? 면에서는 훨씬 나을 것 같아요! 다만 사용처에서 modal 훅을 반드시 호출해줘야 모달을 사용할 수 있다는 점이 조금 아쉬워서 고민이 되네요..! 
아니면 제가 케빈이 말하는 방식을 잘못 이해하고 있는 걸까요 ㅠㅠ

2023-06-08 17:53 UTC, woo-jk commented
안녕하세요 케빈! 꼼꼼한 피드백 감사합니다 ㅎㅎ

케빈의 깃헙 아이디 문제를 꼭 해결하길 바랄게요 ㅠㅠ

케빈이 주신 피드백을 바로 반영해보고 싶었지만 레벨 인터뷰로 인해 하루 건너 반영을 했습니다.. 빠른 반영을 못해 아쉽네요..🥲

아 그리고 코멘트로 주신 피드백은 대부분 반영했지만 UX 피드백은 조금 더 시간이 필요할 것 같아 일단 먼저 리뷰 요청을 드립니다. 방학 기간 동안 UX 피드백을 꼭 반영하겠습니다!

2023-06-10 07:56 UTC, jeoongbin approved these changes
안녕하세요 룩소~
수정해주신 코드 잘 봤습니다 확실히 가독성이 훨씬 올라간거 같아요!

방학기간에 리팩토링 및 개선을 하신다고 하셨으니 하시고 언제든지 끝나고 디엠주시면 같이 또 볼수있으면 좋겠네요.

몇가지 질문드렸는데, 미션은 머지가 되지만 답변 달아주시면 확인 해보겠습니다.
마지막 미션까지 하느라 고생많으셨습니다. 앞으로 룩소의 여정 응원할게요 👍

2023-06-10 07:56 UTC, jeoongbin commented on src/components/cart/CartList/CartList.tsx
> +  useResetCartWhenServerChange();
아하 그런 이유가 있다면 충분히 납득됩니다!

2023-06-10 07:56 UTC, jeoongbin commented on src/components/common/Modal/Modal.tsx
> +  };
룩소 말대로 하시면  모달을 외부해서 디펜던시가 있는상태에서 어떻게 끌수 있을까요??

2023-06-10 07:56 UTC, jeoongbin commented on src/components/cart/PaymentAmount/usePaymentAmount.ts
> +  const deliveryFee = checkedCartIdList.length ? 3000 : 0;
간단하게 usePaymentAmount 사용처에서 변수로 배송비를 받고, 없으면 3000원으로 처리하면 되지 않을까 생각했습니다.

2023-06-10 10:41 UTC, woowahan-cron approved these changes
케빈의 계정 이슈로 크론이 대신 달려왔어요~!!!🏆🏃🏼‍♂️
고생하셨습니다. 레벨3에서 룩소의 활약을 기대해 보겠습니다!

2023-06-10 10:42 UTC, merged