[2단계 - 장바구니 협업] 해리(엄지혁) 미션 제출합니다.
woowacourse/react-shopping-cart-prod pull request #43
Opened 2022-06-09 07:27 UTC by jihyeok-um

# 장바구니 협업 step2

안녕하세요! 발리스타님, 해리입니다.
아직 step1 리뷰도 도착하지 않았는데 step2를 제출하게되어 아쉽네요 ㅠㅠ
이번에도 배포를 따로 하지 못해서 로컬에서 구동을 해주셔야할 것 같습니다 

## 필수 요구사항

- [x] 로컬 기반의 장바구니를 서버 기반으로 변경
- [x] API 호스트를 변경해 모든 백엔드 크루들의 API를 테스트할 수 있어야한다.

## 백엔드와의 API SPEC 협의사항

[API SPEC](https://www.notion.so/API-SPEC-50fd99cc2ca9486ca5b83ed1958b6a6f)
[API SPEC 정리ver.](https://chrome-tune-f34.notion.site/API-SPEC-527efdf45ab04c389308ddbc28b56cc1)

## 구현한 기능 목록

step2 에서 새로운 기능을 추가하지 않고, 백엔드와의 협업을 통해 네 명의 API가 정상 작동하도록만 해주었습니다!

## 리뷰가 늦어질 시 미리 수정할 사항

혹시 이번에도 리뷰가 늦어질 예정이시라면, 따로 DM을 드려서 확인 후에 리팩토링을 먼저 진행해주려합니다!
리팩토링 및 사용성 등등 개선 예정인 내용들은 아래와 같습니다!

### 리팩토링

- [ ] 비동기 로직 컴포넌트에서 분리 -> 리덕스 활용 (미들웨어..)
- [ ] 컴포넌트가 가지고 있는 로직 커스텀 훅으로 분리
- [ ] 비동기 에러 및 성공 메시지가 알맞은 상황에 출력되도록 수정
- [ ] `alert`를 `snackbar`로 교체

### step2 백엔드 API 사용 후 상황에 따른 추가사항

- [ ] accessToken이 없을 때 토큰이 필요한 요청을 보내면 로그인 창으로 이동시켜주기
- [ ] accessToken 쿠키, 세션, 로컬 스토리지 중 하나에 저장하기

2022-06-12 03:52 UTC, Vallista requested changes
안녕하세요 해리님~

ㅠㅠ 제가 바빠서 1단계를 못봤네요.. 저에게 돌을 던지셔도 됩니다..
대신 맛난거 사드릴게요. 언제든지 연락주세요.

---

1단계와 2단계, 그리고 전체 코드를 확인했습니다 :)
역시 지난 미션을 거치면서 많은 성장을 하신 것 같아요~

다만 몇 가지 전반적으로 수정해볼 필요성이 있는 부분을 짚어보도록 하겠습니다 :)

# 피드백

- API 로직이 페이지에 있습니다. 관심사의 분리를 위해 API 레이어를 만드시고, 따로 로직을 관리해주세요. 그리고 호스트는 .env.development 등을 만들어서 환경에 대한 분리도 해주면 좋겠습니다 :) https://create-react-app.dev/docs/adding-custom-environment-variables/
- 커스텀훅을 조금 더 과감히 썻으면 좋겠습니당. 페이지에 비동기 로직이나 access token등 필요없는 로직들이 있는데, 달아둔 코멘트를 보고 슥 수정해주시면 좋을 것 같아요.
- styled component theme provider를 사용해 테마를 넣어주고, COLOR를 임포트해서 쓰지 않으면 좋겠습니다. 이미 있는 기능이에요!

---

나머지는 코드 라인에 피드백을 남겨두었습니다 :)

2022-06-12 03:52 UTC, Vallista commented on src/components/Header.jsx
> +import { COLORS } from '../styles/colorPalette';
`import { COLORS } from '../styles/colorPalette';` 형태로 제공되면 어떤 문제가 발생할까요?

styled-component엔 theme provider가 있을텐데요!

2022-06-12 03:52 UTC, Vallista commented on src/components/Loading.jsx
> +import { COLORS } from '../styles/colorPalette';
모든곳에서 이렇게 참조하고 있군요! 위의 discussion을 참조하세요~

2022-06-12 03:52 UTC, Vallista commented on src/components/ShoppingItem.jsx
> +    updateItemQuantity(id, quantity + 1, accessToken);
accessToken을 여기서 보내는게 맞을까요? 제가 생각하기에 useCart에서 내부적으로 처리하는게 맞지 않을까 해요~

2022-06-12 03:52 UTC, Vallista commented on src/constants/index.js
> +const API_ZERO = 'http://ec2-13-124-88-137.ap-northeast-2.compute.amazonaws.com:8080/api';
Object.freeze 로 enum 형태로 관리하는건 어떨까요?

2022-06-12 03:52 UTC, Vallista commented on src/constants/index.js
>  const SERVER_PATH = {
여기도 변경되는게 딱히 없다면 Object.freeze로 enum임을 명시합시다

2022-06-12 03:52 UTC, Vallista commented on src/hooks/useCart.js
>  const useCart = () => {
아주 좋네요~ 비즈니스 로직을 훅스로 녹이는 것이 좋습니다 :)

2022-06-12 03:52 UTC, Vallista commented on src/hooks/useCart.js
> +  const addItem = (id, accessToken) => {
accessToken은 외부에서 받기보다, useCart에서 처리하는게 낫겠어요!

2022-06-12 03:52 UTC, Vallista commented on src/index.jsx
>    if (process.env.NODE_ENV === 'development') {
이 로직은 메인 안에 있기보다, 메인 밖에 있는게 낫지 않을까요?

2022-06-12 03:52 UTC, Vallista commented on src/pages/LoginPage.jsx
> +      alert(error.response.data.message);
alert(error.response.data.message); 을 통해 나타내주는 것은 좋지만,
개발 상에서도 이 부분이 에러임을 명확하게 알 수 있도록 로그를 남기거나
어떤 상태를 변경하는 등. custom error를 만들 필요는 없을까요?

https://ko.javascript.info/custom-errors

2022-06-12 03:52 UTC, Vallista commented on src/pages/LoginPage.jsx
> +          placeholder="영문자(대,소), 숫자, 특수기호 조합을 입력하세요"
placeholder도 message로 관리할 필요성이 없을까요?

2022-06-12 03:52 UTC, Vallista commented on src/pages/ModifyPasswordPage.jsx
> +          headers: { Authorization: `Bearer ${accessToken}` },
`headers: { Authorization: `Bearer ${accessToken}` },` 를 페이지에서 넣어주는게 맞는걸까요? 또한, axios.patch를 여기서 해주는게 맞을까용?

2022-06-12 03:52 UTC, Vallista commented on src/pages/ModifyUserInfoPage.jsx
> +      await axios.patch(
전반적으로 페이지에서 호출하는 비동기 로직들은, 관심사의 분리를 해서 커스텀 훅에 넣어주는게 좋겠어요 :)

2022-06-12 03:52 UTC, Vallista commented on src/pages/ProductDetailPage.jsx
> +  const isCart = cartList.some((cartItem) => {
"isCart" 가 맞는 이름일까요?

2022-06-12 03:52 UTC, Vallista commented on src/pages/ProductDetailPage.jsx
>    const cartList = useSelector(({ cart }) => cart.data);
"cartList" 는 카트의 복수 집합을 나타내는 것 같아요.
카트는 하나고, 아이템이 담기는 것이니
cartItemList 정도가 더 낫지 않을지..

2022-06-12 03:52 UTC, Vallista commented on src/pages/ProductDetailPage.jsx
>    const onClickCartButton = () => {
여기는 on-* 이 맞을까요?? on은 어디에 쓰이는 전치사인가요?

2022-06-12 03:52 UTC, Vallista commented on src/pages/ProductListPage.jsx
> +      deleteItem(id, accessToken);
여기 페이지는 래핑이 되어있군요!

2022-06-12 03:52 UTC, Vallista commented on src/pages/ProductListPage.jsx
> +  const idSetInCart = useMemo(() => new Set(cartList.map((cart) => cart.name)), [cartList]);
메모이제이션이기 때문에 어떤 데이터를 가져온다(메모리에서)는 느낌으로 명명하는게 좋겠어요~
idSetInCart는.. 이해가 잘 안되는 네이밍이네요 ㅠ

Set도 결국엔 오브젝트고, 리스트기 때문에 cartProductNames 혹은 cartProductNameList 정도가 맞지 않을지!

추가적으로, ~s 와 ~List가 언제 붙는지도 고민해보면 좋겠어요.

2022-06-12 03:52 UTC, Vallista commented on src/pages/ProductListPage.jsx
> +  useEffect(() => {
이런 로직들은 페이지가 아니라 커스텀 훅으로 보내는건 어떨까요?

2022-06-12 03:52 UTC, Vallista commented on src/pages/ProductListPage.jsx
> +              handleCartItem(product.id, idSetInCart.has(product.name), accessToken)
`handleCartItem(product.id, idSetInCart.has(product.name), accessToken)`

레이아웃 로직에선 accessToken이 안보이는게 낫지 않을까요?

2022-06-12 03:52 UTC, Vallista commented on src/pages/ProductListPage.jsx
>    if (isLoading) return <Loading />;
isLoading, isError 등 각각 boolean으로 관리하는 것보다, 하나의 상태를 만들고 그 상태 안에 여러 개를 enum으로 관리해서 만드는게 좋지 않을까요?

2022-06-12 03:52 UTC, Vallista commented on src/pages/ShoppingCartPage.jsx
> +import { COLORS } from '../styles/colorPalette';
import { COLORS } from '../styles/colorPalette'; 는 최대한 쓰지말고, theme provider를 이용합시다..

2022-06-12 03:52 UTC, Vallista commented on src/pages/ShoppingCartPage.jsx
> +  const accessToken = useSelector(({ user }) => user.accessToken);
`const accessToken = useSelector(({ user }) => user.accessToken);` 엑세스 토큰은 useUser 라는 훅을 만들고, useUser를 useCart에서 가져와서 사용하고, useCart에서 모든 데이터를 결합해 사용해줍시다.

이렇게 되면 페이지에선 짜잘한걸 안봐도 돼요!

페이지는 "레이아웃을 조합" 하는것만 담당하기로 해요

2022-06-12 03:52 UTC, Vallista commented on src/styles/colorPalette.js
> +const COLORS = {
https://styled-components.com/docs/advanced 이걸 사용합시다아

2022-06-14 09:47 UTC, jihyeok-um commented on src/components/Header.jsx
> +import { COLORS } from '../styles/colorPalette';
일단 고민을 좀 해보고 명확한 답이 나오지 않아 적용해보고 궁금한 점을 질문해보기로 했습니다!

[`refactor: 전역 COLOS -> ThemeProvider 활용으로 변경`](https://github.com/jihyeok-um/react-shopping-cart-prod/commit/fc40e79f76c6b6b810af212b850d8d761804425c)

먼저, `COLORS` 같은 변수를 직접 전역에서 `import` 해와서 쓰는 것의 문제가 무엇일까? 라고 생각을 해봤을 때, 말그대로 어느 곳에서나 사용할 수 있는 전역에서 직접 가져오는 것이 문제가 아닐까? 라는 생각을 했습니다. 
리액트에서 props가 많다고 상위 컴포넌트가 아닌 직접 전역에서 `import` 해와서 쓰지 않고 `ContextAPI` 등을 활용하듯이 여기서도 비슷한 역할을 해줄 수 있는 `ThemeProvider`를 사용해주는 것이 같은 맥락이라는 생각이 들었습니다!

위의 이유를 메인으로 잡고.. 다른 서브 이유를 생각해보자면, `theme`등을 변경하기가 더 수월하다 정도가 떠올랐습니다!

2022-06-14 09:47 UTC, jihyeok-um commented on src/components/Loading.jsx
> +import { COLORS } from '../styles/colorPalette';
위에 코멘트 남겼습니다!

2022-06-14 09:48 UTC, jihyeok-um commented on src/pages/ShoppingCartPage.jsx
> +import { COLORS } from '../styles/colorPalette';
위에 코멘트 남겼습니다!

2022-06-14 09:48 UTC, jihyeok-um commented on src/styles/colorPalette.js
> +const COLORS = {
위에 코멘트 남겼습니다!

2022-06-14 20:18 UTC, jihyeok-um commented on src/index.jsx
>    if (process.env.NODE_ENV === 'development') {
수정했습니다! 역할 상으로 봐도 밖에서 해주는게 더 나을 것 같네요!

[`refactor: mockWorker 로직 메인 함수 밖으로 빼기`](https://github.com/jihyeok-um/react-shopping-cart-prod/commit/d64b4f4743847b7a228c28f46d1d74e9ee197883)

2022-06-14 20:20 UTC, jihyeok-um commented on src/components/ShoppingItem.jsx
> +    updateItemQuantity(id, quantity + 1, accessToken);
중간에 `useUser` 라는 커스텀 훅을 만들어 useCart가 내부에서 `useUser`를 통해 `accessToken`을 가져와 내부적으로 처리하도록 수정해주었습니다!

[`refactor: 비동기 로직, accessToken 컴포넌트에서 분리`](https://github.com/jihyeok-um/react-shopping-cart-prod/commit/7d2559330e3f60cf6340bc38f878eb7c3924e049)

2022-06-14 20:20 UTC, frontend-jihyeok-um commented on src/hooks/useCart.js
> +  const addItem = (id, accessToken) => {
위와 마찬가지로 처리해주었습니다!

[`refactor: 비동기 로직, accessToken 컴포넌트에서 분리`](https://github.com/jihyeok-um/react-shopping-cart-prod/commit/7d2559330e3f60cf6340bc38f878eb7c3924e049)

2022-06-14 20:23 UTC, frontend-jihyeok-um commented on src/pages/ModifyPasswordPage.jsx
> +          headers: { Authorization: `Bearer ${accessToken}` },
비동기 처리와 관련된 로직들은 컴포넌트나 페이지에서 따로 빼주었습니다!
커스텀훅 -> 비동기 액션 -> 동기 액션 -> 리듀서
로 컴포넌트나 페이지에서는 커스텀훅만 불러서 처리할 수 있도록 해주었습니다!

[`refactor: 비동기 로직, accessToken 컴포넌트에서 분리`](https://github.com/jihyeok-um/react-shopping-cart-prod/commit/7d2559330e3f60cf6340bc38f878eb7c3924e049)

2022-06-14 20:23 UTC, jihyeok-um commented on src/pages/ModifyUserInfoPage.jsx
> +      await axios.patch(
> 비동기 처리와 관련된 로직들은 컴포넌트나 페이지에서 따로 빼주었습니다!
커스텀훅 -> 비동기 액션 -> 동기 액션 -> 리듀서
로 컴포넌트나 페이지에서는 커스텀훅만 불러서 처리할 수 있도록 해주었습니다!

위 코멘트와 같을 것 같습니다!

[`refactor: 비동기 로직, accessToken 컴포넌트에서 분리`](https://github.com/jihyeok-um/react-shopping-cart-prod/commit/7d2559330e3f60cf6340bc38f878eb7c3924e049)

2022-06-14 20:26 UTC, jihyeok-um commented on src/pages/ProductListPage.jsx
> +              handleCartItem(product.id, idSetInCart.has(product.name), accessToken)
> 중간에 유저에 관한 정보를 처리하는 `useUser` 라는 커스텀 훅을 만들어 useCart가 내부에서 `useUser`를 통해 `accessToken`을 가져와 내부적으로 처리하도록 수정해주었습니다!

이제 `accessToken`은 커스텀 훅 `useUser`에서만 가져오고, 컴포넌트 레벨에서는 사용되지 않고 필요로하는 로직들만 `useUser`에서 가져옵니다!

[`refactor: 비동기 로직, accessToken 컴포넌트에서 분리`](https://github.com/jihyeok-um/react-shopping-cart-prod/commit/7d2559330e3f60cf6340bc38f878eb7c3924e049)

2022-06-14 20:27 UTC, jihyeok-um commented on src/pages/ShoppingCartPage.jsx
> +  const accessToken = useSelector(({ user }) => user.accessToken);
> 중간에 유저에 관한 정보를 처리하는 `useUser` 라는 커스텀 훅을 만들어 useCart가 내부에서 `useUser`를 통해 `accessToken`을 가져와 내부적으로 처리하도록 수정해주었습니다!
> 이제 `accessToken`은 커스텀 훅 `useUser`에서만 가져오면서, 컴포넌트 레벨에서는 사용하지 않고 필요로하는 커스텀 훅이나 비즈니스 로직들에서만 `useUser`에서 가져옵니다!

[`refactor: 비동기 로직, accessToken 컴포넌트에서 분리`](https://github.com/jihyeok-um/react-shopping-cart-prod/commit/7d2559330e3f60cf6340bc38f878eb7c3924e049)

2022-06-14 21:36 UTC, jihyeok-um commented on src/pages/ProductListPage.jsx
> +  useEffect(() => {
각자 역할에 맞는 곳으로 이동해서 컴포넌트에서 관련 로직을 가지고 있지 않도록 해주었습니다!

[`refactor: useEffect 커스텀 훅으로 이동`](https://github.com/jihyeok-um/react-shopping-cart-prod/commit/318abf9eba24f2e40e7a2f550b65454cbcb36831)

2022-06-14 21:38 UTC, jihyeok-um commented on src/pages/ProductListPage.jsx
> +      deleteItem(id, accessToken);
혹시 제가 뭘로 래핑이 되어있는건지 이해가 안 되어서 그런데 좀 더 자세히 말씀해주실 수 있나요? ㅠㅠ

2022-06-15 06:46 UTC, jihyeok-um commented on src/constants/index.js
> +const API_ZERO = 'http://ec2-13-124-88-137.ap-northeast-2.compute.amazonaws.com:8080/api';
```javascript
const API_URL = Object.freeze({
  API_ZERO: 'http://ec2-13-124-88-137.ap-northeast-2.compute.amazonaws.com:8080/api',
  API_KILLER_WHALE: `http://13.124.30.129:8080/api`,
  API_AWESOME_O: `http://ec2-15-164-104-189.ap-northeast-2.compute.amazonaws.com:8080/api`,
  API_ROOKIE: `http://ec2-15-164-103-26.ap-northeast-2.compute.amazonaws.com:8080/api`,
});

const SERVER_PATH = Object.freeze({
  PRODUCTS: `${API_URL.KILLER_WHALE}/products`,
  CART: `${API_URL.KILLER_WHALE}/carts`,
  CART_PRODUCT: `${API_URL.KILLER_WHALE}/carts/products`,
  USER: `${API_URL.KILLER_WHALE}/customers`,
  LOGIN: `${API_URL.KILLER_WHALE}/login`,
  PASSWORD: `${API_URL.KILLER_WHALE}/customers/password`,
  ME: `${API_URL.KILLER_WHALE}/customers/me`,
});

const ROUTES_PATH = Object.freeze({
  HOME: '/',
  DETAIL: '/product-detail/:id',
  DETAIL_LINK: '/product-detail/',
  CART: '/shopping-cart',
  LOGIN: '/login',
  SIGN_UP: '/sign-up',
  USER_INFO: '/user-info',
  MODIFY_PASSWORD: '/modify-password',
  MODIFY_USER_INFO: '/modify-user-info',
});
```

말씀해주신 부분은 일단 고쳐봤습니다!
고민이 생겼는데 무엇부터 무엇까지 `Object.freeze`를 해주는게 좋을까? 하는 생각이 들었습니다.
바뀌지 않아야 된다는 측면에서 `constants.js`에 있는 모든 객체에 적용해줄 수도 있겠지만, 이런 식으로 관리해보는 것이 처음이라 맞는지 헷갈리기도 합니다. 발리스타님은 혹시 현업에서 어떤 방식으로 관리하시나요?

2022-06-15 06:46 UTC, jihyeok-um commented on src/constants/index.js
>  const SERVER_PATH = {
위에 코멘트 남겼습니다!

2022-06-15 06:59 UTC, jihyeok-um commented on src/pages/LoginPage.jsx
> +          placeholder="영문자(대,소), 숫자, 특수기호 조합을 입력하세요"
고민을 조금 해봤는데, 저는 상수화를 할 때 두 가지를 생각합니다.
1. 맥락이 없어 알아 볼 수 없는 값이라 변수명으로 식별을 해야하는 값인가?
2. 여러번 (최소 2번 이상) 재활용 되는 값인가?

보통 둘 중 하나만 해당이 되어도 상수화를 해주는 편인데, 2번에 충분히 해당하는 것 같아서 상수화하여 관리하도록 수정했습니다!
발리스타님은 발리스타님의 상수화 기준이 있으신가요?

[`refactor: placeholder 텍스트 상수화하여 관리`](https://github.com/jihyeok-um/react-shopping-cart-prod/commit/899ef38ed3f540fff54ee2f5f55c770696f340b2)

2022-06-15 07:17 UTC, jihyeok-um commented on src/pages/ProductDetailPage.jsx
>    const onClickCartButton = () => {
분명히 `on-`이 아니라 `handle-`을 써야하는 명확한 이유가 있었고, 그렇게 사용하고 있었는데
협업 과정에서 페어 코드를 가져오느라 이것저것 뒤섞인 부분이 있네요 ㅠㅠ

명확한 이유가 떠오르지 않아 아래 링크를 참고했습니다
> https://stackoverflow.com/questions/60048249/what-is-the-right-name-of-event-handler-onclick-or-handleclick

결론은 최소한 "리액트"에서는 props의 속성을 표현할 때는 `on-` 접두어를 붙이고, 어떤 이벤트에 대응하는 함수를 표현할 때는 `handle-` 접두어를 붙인다고 하네요!

2022-06-15 07:30 UTC, jihyeok-um commented on src/pages/ProductDetailPage.jsx
> +  const isCart = cartList.some((cartItem) => {
매우 흡족한 이름은 아니지만... 의사소통이 조금 더 원활할 것 같게 바꿔봤습니다!
상품이 장바구니에 들어있는지를 `boolean`으로 알려주는 변수이니 `isCart`에서 `isProductInCart`로 바꾸었습니다

[`refactor: isCart -> isProductInCart`](https://github.com/jihyeok-um/react-shopping-cart-prod/commit/4910d490b2e66286ffd13cacc8dd5ec101ba0454)

2022-06-15 07:33 UTC, jihyeok-um commented on src/pages/ProductDetailPage.jsx
>    const cartList = useSelector(({ cart }) => cart.data);
확실히 헷갈릴 수도 있는 이름인 것 같아 바로 변경해주었습니다!

[`refactor: cartList -> cartItemList 변수명 수정`](https://github.com/jihyeok-um/react-shopping-cart-prod/commit/e211bc6ada9d8f2b159a04cb7d5c3937eea11bfe)

2022-06-15 08:02 UTC, jihyeok-um commented on src/pages/ProductListPage.jsx
> +  const idSetInCart = useMemo(() => new Set(cartList.map((cart) => cart.name)), [cartList]);
사실 제가 봐도 잘 이해가 안 되고,,, 심지어 읽기도 힘든 네이밍이었던 같습니다.
`cart`에 들어가있는 상품들의 이름을 리스트로 만든거니 cartItemNameList (`cartProduct`보다는 주로 이 미션에 `cartItem`이라는 네이밍이 많아서 통일해주려했습니다)로 했습니다.

`memoizedCartItemNameList` 나 `cartItemNames`도 고민해보았지만, 전자는... 안그래도 이름이 긴데 굳이 `memozied`를 붙여줘야할까? 라는 생각때문에, 후자는 제가 보통 여러개를 모아놓은 변수의 suffix는 헷갈리지 않게 `-s`가 아니라 `-list`로 통일하는 편이라 결국 `cartItemNameList`가 되었습니다!

> 추가적으로, ~s 와 ~List가 언제 붙는지도 고민해보면 좋겠어요.

이건 명확히 찾아보고 써본 기억이 없어서 검색을 해봤는데 검색어가 잘못되었는지 원하는 답을 주는 문서를 찾을 수가 없네요..
저는 `~s`는 여러 개의 같은 용도의 파일을 모아 놓는 폴더 `components` 등을 제외하고는 변수명에서는 `~List`로 통일하는 것 같습니다!

2022-06-15 09:42 UTC, jihyeok-um commented on src/pages/ProductListPage.jsx
>    if (isLoading) return <Loading />;
이걸... 의도하신게 맞는지 모르겠네요 ㅎㅎ ㅠㅠ
```javascript
// useFetch.js

const initialState = {
  result: null,
  isLoading: true,
  isError: false,
};

function useFetch(url) {
  const [response, setResponse] = useState(initialState);
  const { accessToken } = useUser();

  const requestData = async () => {
    try {
      const { data } = await axios({
        method: 'get',
        url,
        headers: { Authorization: `Bearer ${accessToken}` },
      });
      setResponse((prevState) => {
        return {
          ...prevState,
          result: data,
        };
      });
    } catch (error) {
      setResponse((prevState) => {
        return {
          ...prevState,
          isError: true,
        };
      });
    } finally {
      setResponse((prevState) => {
        return {
          ...prevState,
          isLoading: false,
        };
      });
    }
  };

  useEffect(() => {
    requestData();
  }, []);

  return response;
}

export default useFetch;
```

```javascript
// productListPage.jsx

function ProductListPage() {
  const { result: productList, isError, isLoading } = useFetch(SERVER_PATH.PRODUCTS);
  const { cartItemList, addItem, deleteItem } = useCart();
  const cartItemNameList = useMemo(
    () => new Set(cartItemList.map((cart) => cart.name)),
    [cartItemList]
  );

  const handleClickCartItem = (id, isProductInCart) => {
    if (isProductInCart) {
      deleteItem(id);
      alert(MESSAGE.REMOVE);
      return;
    }
    addItem(id);
    alert(MESSAGE.ADD);
  };

  if (isError) return <h1>error</h1>;
  if (isLoading) return <Loading />;

  return (
    <StyledContent>
      <StyledGridContainer>
        {productList.map((product) => (
          <Product
            key={product.id}
            productData={product}
            handleCartItem={() =>
              handleClickCartItem(product.id, cartItemNameList.has(product.name))
            }
            isProductInCart={cartItemNameList.has(product.name)}
          />
        ))}
      </StyledGridContainer>
    </StyledContent>
  );
}
```

[`refactor: fetch 결과 하나의 state로 통합`](https://github.com/jihyeok-um/react-shopping-cart-prod/commit/07542bcb5401d2d967a4441e74adb342610ffc8f)

2022-06-15 10:16 UTC, jihyeok-um commented
어... 제 목적은 호스트 주소를 숨기는 거였는데, 제가 생각한만큼 완벽하게 숨겨지지는 않는군요.. ㅠㅠ
최소한 깃허브에 떡하니 호스트 주소가 올라가지는 않으니 차근차근 공부해봐야겠습니다!

> 그리고 호스트는 .env.development 등을 만들어서 환경에 대한 분리도 해주면 좋겠습니다 :)

[`refactor: 호스트 env.development 를 통해 숨기기`](https://github.com/jihyeok-um/react-shopping-cart-prod/commit/cdcd0a7366107e738770e6acd66fa5c5b7210960)

2022-06-15 10:49 UTC, jihyeok-um commented on src/pages/LoginPage.jsx
> +      alert(error.response.data.message);
링크를 보면서 커스텀 에러 클래스를 만들어서 처리해주려했지만...
내일 10시까지 다시 리뷰 요청을 보내려면, 계층적인 커스텀 에러 클래스까지 만들어 구체적인 에러까지 대응할 시간은 없다는 생각이 들어서 간단히 개발 도중에 에러에 관한 정보를 `console.log`로 찍어주는 함수로 대체했습니다 ㅠㅠ

```javascript
function handleErrorLog(error) {
  if (process.env.NODE_ENV !== 'development') {
    return;
  }

  if (error.response) {
    // 요청이 이루어졌으며 서버가 2xx의 범위를 벗어나는 상태 코드로 응답했습니다.
    console.log(error.response.data);
    console.log(error.response.status);
    console.log(error.response.headers);
  } else if (error.request) {
    // 요청이 이루어 졌으나 응답을 받지 못했습니다.
    console.log(error.request);
  } else {
    // 오류를 발생시킨 요청을 설정하는 중에 문제가 발생했습니다.
    console.log('Error', error.message);
  }
  console.log(error.config);
}

export default handleErrorLog;
```

[`feat: 에러에 관한 정보를 로그로 찍어주는 함수 구현`](https://github.com/jihyeok-um/react-shopping-cart-prod/commit/537762d7e5ebe3a4c487eaae49828d90d121b3ec)

2022-06-28 00:55 UTC, pocojang approved these changes
@jihyeok-um 

기간도 한참 지났고 이미 오프라인에서 1대1 리뷰를 받은 것으로 들었습니다.
이만 머지할테니 추가 리뷰가 진행되기로 약속되어있다면 코멘트로 나눠보세요

레벨2 기간 고생 많으셨습니다 👍

2022-06-28 00:55 UTC, merged