[2단계 - 장바구니 협업] 우디(우정민) 미션 제출합니다
woowacourse/react-shopping-cart-prod pull request #51
Opened 2022-06-09 08:19 UTC by greenblues1190

안녕하세요 혜인티님, 우디입니다.

이번 스텝에서는 백엔드와 협업하여 장바구니 웹앱에 api를 연결했습니다. 미숙한 설계로 헤매기도 하고 많이 어설픈 코드가 나왔네요. 많은 것들을 배운 미션이었습니다!

## 데모사이트

[링크](http://woojeongmin.com/react-shopping-cart-prod/)

감사합니다.

2022-06-11 11:58 UTC, HyeonaKwon requested changes
안녕하세요 우디! 2단계 미션 잘 봤습니다 :)
코멘트는 몇개 없지만 확인해주시면 될 것 같습니다!

#### 데모피드백
1. 비밀번호칸에서 아무 입력값도 없을 때 백버튼 누르면 다음 tabindex 로 넘어가는 것 같네요.
2. 생년월일 인풋을 클릭했을 때 달력이 나왔으면 좋겠네요.
3. 회원가입에서 다음으로 에서 넘어가지를 않네요.
4. 비로그인 상태에서 구매하기 클릭 시 제품안내 페이지로 이동하는데요, 안내가 부족한 것 같습니다.

2022-06-11 11:58 UTC, HyeonaKwon commented on src/components/Auth/Auth.tsx
> +type Props = React.PropsWithChildren<{ option?: boolean }>;
option 이라는 의미가 불분명한 것 같아요!

2022-06-11 11:58 UTC, HyeonaKwon commented on src/components/Input/Input.tsx
> +  useImperativeHandle(ref, () => inputRef.current as HTMLInputElement);
forwardRef 인데 부모에게 받은 ref 가 아니라 다시 ref  를 생성해서 넣어주는 이유가 뭘까요?
그리고 이 훅을 사용한 이유도 궁금하네요!

2022-06-11 11:58 UTC, HyeonaKwon commented on src/hooks/useForm.ts
> +export default useForm;
음.. 모든 form 을 포함시키기 위해서인지는 모르겠으나 코드가 너무 복잡해서 잘 읽히지가 않네요ㅠ!
watchingValues 를 관리하는 이유도 궁금합니다!

2022-06-11 11:58 UTC, HyeonaKwon commented on src/pages/MainPage/useProductList.ts
> +  const outOfStockList = productList.filter((product) => product.stock <= 0);
👍

2022-06-15 22:59 UTC, greenblues1190 commented on src/components/Input/Input.tsx
> +  useImperativeHandle(ref, () => inputRef.current as HTMLInputElement);
타입스크립트에서 ref.current가 readonly라 인풋요소를 할당할 수 없다는 에러가 있었는데 다시 확인하니 없어졌네요. useRef에 전달한 제네릭이 잘못되어 발생한 에러였던 것 같습니다. 에러가 발생하지 않아 삭제했습니다.

useImperativeHandle은 [스택오버플로우 글](https://stackoverflow.com/questions/57278120/using-react-callback-ref-with-forwarded-ref)을 참고하여 ref의 current에 인풋요소를 전달하기 위해 사용했습니다.

2022-06-15 23:03 UTC, greenblues1190 commented on src/components/Auth/Auth.tsx
> +type Props = React.PropsWithChildren<{ option?: boolean }>;
shouldLogin으로 수정했습니다!

2022-06-15 23:16 UTC, greenblues1190 commented on src/hooks/useForm.ts
> +export default useForm;
비제어로 폼을 관리하기 때문에 제출 전까지는 인풋요소의 값을 알 수 없었습니다. 때문에 값이 변할 때마다 확인이 필요한 인풋요소들은(watch 속성을 true로 준 인풋) change 이벤트가 발생할 때마다 watchingValues라는 상태에 값을 복사하도록 했습니다.

훅의 매개변수와 export 형태는 react-hook-form를 참고하여 구현했습니다. onSubmit과 onError 콜백 함수를 전달받는 registerForm 함수를 통해 form 요소의 submit 핸들러를 정의해주었습니다. registerInput 함수를 통해 input 요소의 이름과 속성을 전달받으면 이벤트 핸들러들을 만들어 바인딩해주고 인풋 유효성 검사와 이전, 다음 인풋 포커스를 수행하는 inputController ref를 바인딩 해주었습니다.

2022-06-15 23:42 UTC, greenblues1190 commented
> 1. 비밀번호칸에서 아무 입력값도 없을 때 백버튼 누르면 다음 tabindex 로 넘어가는 것 같네요.

이전 요소 포커싱 함수를 만들 때 다음 요소 포커싱 함수의 코드를 붙여넣고 수정하는 과정에서 수정이 안된 부분이 있었습니다. 해당 부분 수정하여 이전 요소 포커싱하도록 했습니다. 81c3709

> 2. 생년월일 인풋을 클릭했을 때 달력이 나왔으면 좋겠네요.

생년월일 인풋 onClick 핸들러에서 `showPicker` 메소드를 트리거하도록 수정했습니다. 78c3b6e

> 3. 회원가입에서 다음으로 에서 넘어가지를 않네요.

아마 생년월일을 입력안하신 것 같네요. 생년월일이 선택입력사항으로 정의했는데 백엔드에서 db 이슈가 있어 생년월일을 입력받지 않으면 에러가 발생한다고 합니다. (빈 문자열을 전달하기로 했는데 db에 최소값인 -199999년이 들어간다고 하네요.) 생년월일까지 입력해주시고 제출 버튼 누르시면 회원가입 가능합니다..!

> 4. 비로그인 상태에서 구매하기 클릭 시 제품안내 페이지로 이동하는데요, 안내가 부족한 것 같습니다.

문구를 상세보기로 수정하였습니다. 5e055d8

2022-06-18 08:20 UTC, HyeonaKwon commented on src/hooks/useForm.ts
> +export default useForm;
아하 그런데 watchingValues 를 관리하는 모습이 결국은 제어 컴포넌트들의 값을 관리하는 것과 비슷하단 생각을 했어요. 결국 그러면 제어 컴포넌트들이 나은거 아닌가? 하는 생각이 들기도 합니다!

2022-06-18 08:23 UTC, HyeonaKwon approved these changes
![image](https://user-images.githubusercontent.com/46472795/174429417-bfddd575-4fd8-4b0b-9be9-42e6d694a58c.png)
생년월일 입력했는데 안넘어가긴 해요ㅠ 한번 확인 부탁드릴게요!
그 이외에는 코멘트 확인했습니다! 일단 머지하도록 하겠습니다~ 고생하셨어요 우디! 👍

2022-06-18 08:23 UTC, merged