[2단계 - 장바구니 협업] 나인(장호영) 미션 제출합니다.
woowacourse/react-shopping-cart-prod pull request #54
Opened 2022-06-09 08:22 UTC by jhy979

작성 중...

2022-06-11 13:06 UTC, HyeonaKwon requested changes
나인 안녕하세요! 마지막 미션에서 뵙네요 :)
특별한 코멘트는 없고 확인만 해주시면 될 것 같습니다! 고생 많으셨어요 ㅎㅎ

#### 데모 피드백
1. 장바구니에 담겼을 때 담겼다는 피드백이 있었으면 좋겠어요.
2. 장바구니에서 수량을 변경하고 다시 들어오면 수량이 이전값이네요.

2022-06-11 13:06 UTC, HyeonaKwon commented on package.json
> +    "sming-payments": "^1.3.5",
요게 뭐죠?!

2022-06-11 13:06 UTC, HyeonaKwon commented on src/component/common/Button/index.jsx
> +      {...rest}
spread props 는 다른 속성들보다도 제일 먼저 작성해주면 좋을 것 같아요~!

2022-06-11 13:06 UTC, HyeonaKwon commented on src/hook/useCartItem.js
> +  const deleteCartItem = (payload, confirmMessage = true) => {
message 는 보통 string 이라 생각되는데요, boolean 으로 설정한 이유가 있을까요?

2022-06-11 13:06 UTC, HyeonaKwon commented on src/page/OrderDetailPage/index.jsx
> +    navigateLoginPage();
isLogin이 true 여도 로그인페이지로 이동하는게 맞나요?

2022-06-11 13:07 UTC, HyeonaKwon commented on package.json
> +    "sming-payments": "^1.3.5",
> 프론트엔드 크루 자스민이 만든 스밍페이 사용하기

앗 요거였군요!

2022-06-11 13:09 UTC, HyeonaKwon commented
> api 에 관련된 모든 정보 -> API_URL, method, body, headers 이런 것들이 떠오르는데 이런 것들이 컴포넌트 밖으로 나가야한다는 말일까요? (그렇다면 이 부분만을 위해서 커스텀훅을 분리해서 사용해야한다는 것일까요?)

컴포넌트에서의 api 호출이 잘못되었다는게 아니라, api를 호출할 때마다 옵션값들을 넣어줘야한다는거에요!
그래서 휴먼에러가 발생할 수도 있고, api url 같은 경우 한 곳에서 관리하는 것이 추후에 변경되었을 때 유지보수가 쉬울텐데 이렇게 컴포넌트마다 사용하고 있다면 관리가 어렵지 않을까 해서 드린 피드백이었습니다!

2022-06-13 11:24 UTC, jhy979 commented on package.json
> +    "sming-payments": "^1.3.5",
맞아요 ㅎㅎ 스밍페이먼츠 신기하죠!

2022-06-13 11:24 UTC, jhy979 commented on src/component/common/Button/index.jsx
> +      {...rest}
앗... 지난번에 피드백 주신 부분인데 제가 전부 확인하지 않았네요 ㅠㅠ

바로 전부 수정하겠습니다!

2022-06-14 00:09 UTC, jhy979 commented on src/page/OrderDetailPage/index.jsx
> +    navigateLoginPage();
`navigateLoginPage` 함수 내부에서 isLogin이 false인 경우에만 이동하도록 했어요!

네이밍이 조금... 애매하다고 저도 생각하긴 했는데 마땅히 떠오르지 않았던 것 같아요.

login 이 안 된 경우에만 이동한다는 의미로 네이밍을 수정하거나

```
if(!isLogin) {
 ...
}
```
처럼 분기를 밖으로 꺼내야 하나의 함수가 하나의 일을 한다고 볼 수 있겠네요...!

2022-06-15 09:07 UTC, jhy979 commented on src/hook/useCartItem.js
> +  const deleteCartItem = (payload, confirmMessage = true) => {
장바구니에서 카트를 삭제할 때 alert 메세지를 `띄울 것이냐 말 것이냐`에 대한 여부를 판단하기 위해서 confirmMessage로 지었습니다.

다만 말씀하신대로 string이 바로 예상이 되네요. showAlert? 이런 느낌으로 네이밍을 가져가는것이 더 좋아보입니다!

2022-06-15 23:40 UTC, jhy979 commented
[fix: 장바구니 재방문 시 수량 1로 변경되는 에러 수정](https://github.com/woowacourse/react-shopping-cart-prod/pull/54/commits/5b06655501a7592e85fecbb72db3c12240490d0c)

반영하였습니다.

전에는 크게 신경 쓰지 않았는데 API 호출과 관련하여 말씀해주신 부분들을 생각해보니 정말 한 곳에 모여 있는 것이 훨씬 나을 것 같다고 생각이 드네요. 

API 호출과 관련된 모든 부분들을 useApiCall이라는 커스텀훅으로 한 파일로 모아 보았는데 

현재는 `useFetch` 내부에서 error, fetch한 data, pending, fetch 함수를 모두 관리하고 있다보니 fetch 함수를 사용할 시점의 관련된 에러, 로딩, 데이터를 제대로 가져오지 못하는 경우들이 발생하더라구요. 

현재 파일에서는 `useCartItem` 이라는 커스텀훅이 Cart와 관련된 API 호출들을 담당하고 있다고 볼 수 있을 것 같아요.

다른 API 호출들도 조금 더 보완해서 수정할 방법을 찾아 봐야겠습니다! 감사합니다 헤인티

2022-06-18 08:27 UTC, HyeonaKwon approved these changes
나인 안녕하세요! 좋은 고민을 하신 것 같아 칭찬의 박수를 드립니다 👏🏻👏🏻

어떻게 모아볼지도 예제 많이 찾아보시면 좋을 것 같아요!
그리고 바꾸신 코드 보니까 `if (isLogin === false )` 이런식으로 비교하는 코드가 보이는데요! 간단하게 `if (!isLogin)` 으로 작성하시면 좋을 것 같습니다 ㅎㅎ

이번 미션 수행하느라 고생 많으셨어요!

2022-06-18 08:27 UTC, merged