[2단계 - 장바구니 협업] 병민(윤병인) 미션 제출합니다.
woowacourse/react-shopping-cart-prod pull request #60
Opened 2022-06-09 08:32 UTC by airman5573

..

2022-06-11 19:45 UTC, lsw1164 requested changes
병민님, 코드 잘봤습니다 
redux 사용법도 익숙해지신 거 같고 장점을 잘 파악하고 계시네요👍
코멘트 확인해주세요!

++
> 상태를 초기화 해야하는 번거로움이 있을것으로 예상됩니다. A페이지에서 비동기 처리후 isSuccess의 상태가 true가 되고, 다른 페이지로 넘어갔을때 isSuccess를 초기화 해주지 않으면, 다시 A페이지로 돌아왔을때 뭔가 해야하는데 isSuccess가 true여서 다른 로직이 실행됩니다. 이거는 정말 어쩔 수 없이 초기화 해줘야 하는것 같은데,,,뭔가 이런식으로 하다보면 코드가 점점 복잡해 지지 않을까? 하는 생각도 듭니다. 예를들어 페이지를 벗어날때라는 이벤트가 발생했을때 초기화를 해줘야 하는데, 어디서 초기화를 했는지 찾기가 좀 어려워지지 않을까...하는 생각이 듭니다. 보통 현업에서 Redux를 쓸때 이 부분이 큰 문제가 되는지 궁금합니다! + (Redux + Thunks) 대신 다른 괜찮은 조합이 있다면 추천 부탁드립니다! 리덕스 힘드네요..

페이지 벗어날 때 초기화 하고 싶다면 [useEffect cleanup](https://ko.reactjs.org/docs/hooks-effect.html#example-using-hooks-1)을 활용해서 초기화 로직을 실행하면 될 거 같아요.



어디서 초기화 했는지 찾기 어려운 건 어떤 의미일까요? 
코드 검색이 불편해서 그럴까요?

비동기 호출 관련해서 Thunks 대신 도움 받을 수 있는 라이브러리는 react-query 나중에 공부해 보시면 어떨까요? ㅎㅎ

2022-06-11 19:45 UTC, lsw1164 commented on src/utils/fetcher.js
> +  static BASE_URL = API_URL;
import가 없던데 API_URL는 어떤거죠?

2022-06-11 19:45 UTC, lsw1164 commented on src/utils/fetcher.js
> +
두 가지 의문이 들었는데요.

1. Fetcher가 accessToken의 관리 책임까지 갖고 있는 걸까요?

2. Fetcher가 LocalStorage에 의존성을 갖고 있는데요.
updateAccessToken에서 accessToken을 LocalStoreage에 저장하지 않는 이유가 있을까요?

2022-06-11 19:45 UTC, lsw1164 commented on src/redux/utils/ApiError.js
> +class ApiError extends Error {
Api 예외 상황에서 쓰는 Error 객체군요 👍

2022-06-11 19:45 UTC, lsw1164 commented on src/index.jsx
> +  accessToken && (await getUser()(store.dispatch));
getUser를 기다릴 때까지 사이트가 아무것도 그리지 않는건가요? 🤔

2022-06-15 03:45 UTC, airman5573 commented on src/utils/fetcher.js
> +  static BASE_URL = API_URL;
[.env.dev](https://github.com/airman5573/react-shopping-cart-prod/blob/airman5573/env/.env.dev) 파일에 있습니다! 

그리고 [webpack에서 DefinePlugin을 사용해](https://github.com/airman5573/react-shopping-cart-prod/blob/859238ae576231754bc2115110e4c1f91c35bdab/webpack/webpack.dev.js#L16) .env.dev파일에 있는 API_URL을 main.js파일에 넣었습니다.

2022-06-15 04:30 UTC, airman5573 commented on src/utils/fetcher.js
> +
1. **Fetcher가 accessToken의 관리 책임까지 갖고 있는 걸까요?**

조금 애매합니다 ㅠ  
Fetcher를 쓸때 accessToken이 매우 자주 사용되기 때문에, LocalStorage에서 accessToken을 가져와서 내부적으로 캐싱하고 때에따라 캐싱된 값을 업데이트 해주고 있습니다. 그래서 Fetcher가 accessToken을 "관리"한다고 해야할지 조금 의문이 듭니다. accessToken을 관리 하는건 LocalStorage이고 Fetcher는 I/O비용을 줄이기 위해 캐싱해서 사용하는 정도가 아닌가 싶습니다.

2. **Fetcher가 LocalStorage에 의존성을 갖고 있는데요.
updateAccessToken에서 accessToken을 LocalStoreage에 저장하지 않는 이유가 있을까요?**

Fetcher가 accessToken을 관리하는 주체가 아니기 때문입니다.  


리뷰어님의 질문을 듣고, Fetcher와 LocalStorage의 의존성을 떨어뜨려야 겠다는 생각이 들었습니다. 또한, 현재 Fetcher를 범용적으로 쓰기가 어렵다는 생각도 들었습니다.  

아래와같이 static을 제거하고 필요할때 initialize해서 쓰는편이 더 나을까요?
```
class Fetcher {
  constructor(accessToken, baseUrl = API_URL) {
    this.baseUrl = baseUrl;
    this.accessToken = accessToken;
  }

  getHeadersWithAccessToken = () => {
    const headers = this.accessToken
      ? {
          Authorization: `Bearer ${this.accessToken}`,
        }
      : {};
    return headers;
  };

  get = (endpoint) => {};

  post = (endpoint, body) => {};

  patch = (endpoint, body) => {};

  delete = (endpoint, body) => {};
}
```

2022-06-15 09:22 UTC, airman5573 commented on src/index.jsx
> +  accessToken && (await getUser()(store.dispatch));
네, 현재는 유저정보를 갖고 온 뒤에 App을 렌더링 하도록 설계했습니다.  
왜냐하면 처음에 잠깐만 기다리면 이후에는 로그인 유무를 검사하는 로직이 없어 깜빡거리는 현상이 줄어들것이라 생각했기 때문입니다.  (특히 header)  
하지만 리뷰어님의 질문을 듣고 '이게 최선일까?' 하는 생각이 들었습니다.  
그래서 이 문제를 해결하는 여러가지 방법을 조사해보았습니다.

## 깜빡여도 괜찮다
**라프텔**  
![laftel-loading-gif](https://develoger.kr/wp-content/uploads/loding-laftel.gif)

**New York Times**
![new-york-times-gif](https://develoger.kr/wp-content/uploads/new-york-times.gif)

라프텔과 NYT모두 로딩 후에 로그인된 유저인지를 확인하는듯 싶습니다.  
라프텔은 괜찮은데, NYT는 로그인 버튼이 꽤나 오래 표시되어 있어서 UI/UX적으로 개선이 필요하다고 생각했습니다.

## 레이아웃으로 승부하기
**Airbnb**
![airbnb](https://develoger.kr/wp-content/uploads/airbnb.gif)

보시다싶이 데스크탑 모드에서도 햄버거 메뉴를 사용하기 때문에 레이아웃에 변화가 없습니다. 이미지만 비동기적으로 바뀔 뿐입니다. 내부적으로는 페이지 로딩 후에 추가로 로그인 상태인지 확인하고 re-render되는것 같습니다만, 사용자에게 그것이 표출되지는 않습니다. 

## 안깜빡이기
**velog**
![velog](https://develoger.kr/wp-content/uploads/velog.gif)

velog는 깜빡이지 않습니다. 레이아웃도 바뀌지 않습니다. chrome에서 js를 꺼도 "로그인" 버튼이 아닌 "새 글 작성" 버튼이 나왔습니다. 저는 어떻게 이럴 수 있는지 궁금했습니다. 다행히! velog는 [오픈 소스](https://github.com/velopert/velog-client)여서 코드를 까볼 수 있었습니다.

### [header.jsx](https://github.com/velopert/velog-client/blob/8f4a030aa69d30674e96584d6b5e64ab6e0b4889/src/components/base/Header.tsx#L20)
3항연산자로 로그인 안된 상태면 "로그인" 버튼을, 로그인 된 상태면 "새 글 작성" 버튼을 보여줍니다.

### [ssrMiddleware.js](https://github.com/velopert/velog-client/blob/8f4a030aa69d30674e96584d6b5e64ab6e0b4889/src/server/ssrMiddleware.ts#L4)

```javascript
const result = await serverRender({
  url: ctx.url,
  cookie: ctx.headers.cookie,
  loggedIn: !!(
    ctx.cookies.get('refresh_token') || ctx.cookies.get('access_token')
  ),
});
```
ssrMiddleware에서 serverRender를 호출합니다.

### [serverRender.js](https://github.com/velopert/velog-client/blob/8f4a030aa69d30674e96584d6b5e64ab6e0b4889/src/server/serverRender.tsx#L86)

serverRender안에서는 서버 사이드 렌더링을 합니다. 

```javascript
const Root = (
    <ChunkExtractorManager extractor={extractor}>
      <HelmetProvider context={helmetContext}>
        <StyleSheetManager sheet={sheet.instance}>
          <Provider store={store}>
            <UncachedApolloProvider client={client}>
              <ApolloProvider client={client}>
                <StaticRouter location={url} context={context}>
                  <App />
                </StaticRouter>
              </ApolloProvider>
            </UncachedApolloProvider>
          </Provider>
        </StyleSheetManager>
      </HelmetProvider>
    </ChunkExtractorManager>
  );
```

여기서 [getDataFromTree](https://www.apollographql.com/docs/react/api/react/ssr/#getdatafromtree)로 Root에서 apollo client로 호출된 요청들을 전부 처리해줍니다.
```javascript
try {
    await getDataFromTree(Root);
  } catch
```

### [useUserLoader.jsx](https://github.com/velopert/velog-client/blob/8f4a030aa69d30674e96584d6b5e64ab6e0b4889/src/containers/base/hooks/useUserLoader.tsx#L11)

여기서 user정보를 가져옵니다

```javascript
const getCurrentUser = useQuery<{ auth: CurrentUser }>(GET_CURRENT_USER);
  const prevUser = useSelector((state: RootState) => state.core.user);

  const user = getCurrentUser.data ? getCurrentUser.data.auth : undefined;

  if (ssrEnabled && user) {
    dispatch(setUser(user));
  }
```

즉, 서버에서 cookie를 바탕으로 유저를 가져와서 렌더링까지 해준 html string을 돌려줬기 때문에 깜빡임 없이 "새 글 작성" 버튼이 나왔다고 생각합니다.

## 결론
1. index.jsx에서 사용자 정보를 가져오지 않고, 사용자 정보가 필요한 곳에서 요청을 보내겠습니다.(수정 커밋 : [8003384](https://github.com/woowacourse/react-shopping-cart-prod/pull/60/commits/800338409edfadcf1e7abbd32bdc58afa178272a))
2. SSR이 제일 좋은 선택지인것 같은데, 지금 미션에서는 구현하기 어렵기 때문에 잠깐 data fetching하는 동안 [header 메뉴에서 아무것도 안보이게 하고, 이후에 가져오면 메뉴를 보이도록](https://github.com/airman5573/react-shopping-cart-prod/blob/800338409edfadcf1e7abbd32bdc58afa178272a/src/components/header/Header.jsx#L68) 하는것이 최선이라고 생각했습니다. 

혹시 더 괜찮은 방법이 있는지, 리뷰어님의 의견이 궁금합니다!

2022-06-15 18:21 UTC, lsw1164 commented on src/utils/fetcher.js
> +  static BASE_URL = API_URL;
오... webpack 기능이군요 DefinePlugin은 처음봐서 그런지 블랙박스 같은 느낌이네요.
IDE에서 쉽게 확인 가능한가요?

2022-06-15 18:31 UTC, lsw1164 commented on src/index.jsx
> +  accessToken && (await getUser()(store.dispatch));
여러 래퍼런스를 참고 및 분석해서 현재 상황에서 적절한 방법을 찾으신 거 같아요 👍

2022-06-15 19:08 UTC, lsw1164 commented on src/utils/fetcher.js
> +
그렇게 하면 의존성은 해결하겠군요 👍
그냥 토큰을 외부에서 주입하게 되면 instance을 계속 새로 만들어야 될 거 같은데. 
그냥 get, post, patch delete에 토큰 파라미터 받아서 utils 함수로 만들어도 될 거 같다는 생각이 들었습니다.

2022-06-16 15:58 UTC, lsw1164 requested changes
-

2022-06-17 05:11 UTC, airman5573 commented on src/utils/fetcher.js
> +  static BASE_URL = API_URL;
IDE에서 전체파일 문자열 검색으로만 확인 가능합니다 ㅠ  

그리고 제가 조금 잘못 말씀드린것이, API_URL을 main.js파일에 넣는다기 보다는 대체 한다고 합니다!  

```javascript
if (!PRODUCTION) {
  console.log('Debug info');
}

if (PRODUCTION) {
  console.log('Production log');
}

// build후

if (!true) {
  console.log('Debug info');
}
if (true) {
  console.log('Production log');
}
```

2022-06-17 06:32 UTC, airman5573 commented on src/utils/fetcher.js
> +
말씀하신대로 accessToken을 각 메서드에 파라미터로 받아 사용했습니다.

```javascript
static get = ({ endpoint, accessToken }) => {
  return fetch(`${this.BASE_URL}/${endpoint}`, {
    headers: { ...this.getHeadersWithAccessToken(accessToken) },
  });
};
```

다만, `LocalStorage.getItem("accessToken")`의 반복이 심해서
```javascript
const accessToken = LocalStorage.getItem("accessToken");
const response = await Fetcher.get({ endpoint: "mycarts", accessToken });
```

[AccessTokenStorage](https://github.com/airman5573/react-shopping-cart-prod/blob/9bd80122bfdba29a5555ad18dd7879b0b8bbc8a5/src/storage/accessTokenStorage.js#L1)를 만들었습니다.  
AccessTokenStorage안에서 LocalStorage를 사용했었는데, 이렇게 되면 또 의존성이 발생해서, 외부에서 storage를 주입받는 식으로 개선했습니다.

2022-06-17 06:40 UTC, airman5573 commented
> 어디서 초기화 했는지 찾기 어려운 건 어떤 의미일까요?
> 코드 검색이 불편해서 그럴까요?

제가 너무 막연한 질문을 드렸었네요!  

페이지를 벗어날때, 혹은 특정 이벤트가 발생했을때 상태를 초기화 해줘야 한다고 생각했습니다.  
다시말해서, useEffect의 cleanup함수 혹은 이벤트 핸들러에서 상태를 초기화 하는 action이 dispatch되야 할텐데,  
이렇게 되면 나중에 코드를 봤을때 어디서 상태를 초기화 하는지 찾기 어렵지 않을까...하는 걱정이 있었습니다. (뭔가 자동으로 되길 바랬던 것이었습니다)  
그런데 이것은 어쩔 수 없는 부분이기도 하고, 그렇게 찾기 어렵지도 않을 것 같다는 생각이 듭니다 :D

2022-06-17 19:02 UTC, lsw1164 approved these changes
병민님, 피드백 반영한 거 확인했습니다.
여러 래퍼런스도 참고하시고 더 좋은 코드에 대해 계속 고민하는 모습을 보니 
앞으로의 성장이 기대되네요 :)
Approve 하겠습니다. 남은 과정도 화이팅입니다~

2022-06-17 19:02 UTC, merged