[2단계 - 장바구니 협업] 하리(이아현) 미션 제출합니다.
woowacourse/react-shopping-cart-prod pull request #70
Opened 2022-06-09 08:47 UTC by daaaayeah

2022-06-13 06:12 UTC, austinpark420 requested changes
안녕하세요 티거!~

step2 구현하시느라 고생많으셨습니다 👍 
코드 관련해서 코멘트 남겨놨으니 확인 부탁드릴게요!!
궁금하신 부분이 있으면 말씀부탁드려요 😄

2022-06-13 06:12 UTC, austinpark420 commented on src/App.tsx
> +        </Route>
깔끔한 예외처리네요 👍

2022-06-13 06:12 UTC, austinpark420 commented on src/pages/Login/index.tsx
> +    const accessToken = await loginAPI(userName, password);
response으로 accessToken만 보내주는건가요?...
이렇게되면 accessToken 값이 잘못된 값이라도 FE에서는 로그인이 성공했다고 간주할텐데요..
BE에서 로그인성공여부 등 좀 더 많은 정보를 FE에게 전달해줘야할것 같습니다.

2022-06-13 06:12 UTC, austinpark420 commented on src/pages/ProductList/index.tsx
> +  }, [dispatch, isLoggedIn]);
dispatch를 두번째 파라미터에 넣으신 이유를 알 수 있을까요?!

2022-06-13 06:12 UTC, austinpark420 commented on src/redux/modules/cart/cartThunk.ts
> +  (item: { id: number; imageUrl: string; name: string; price: number; isSelected: boolean }): any =>
카트에 추가할 때 id, imageUrl, name, price 모든 값을 보내는 이유가 있을까요?!

2022-06-13 06:12 UTC, austinpark420 commented on src/redux/modules/cart/cartThunk.ts
> +  (item: { id: number; imageUrl: string; name: string; price: number; isSelected: boolean }): any =>
any는 안쓰는게 좋겠죠?!

2022-06-13 06:12 UTC, austinpark420 commented on src/redux/modules/cart/cartThunk.ts
> +        alert(ERROR_MESSAGES.REQUEST.ADD_ITEM_TO_CART);
에러메세지를 FE에서 정의하고 있네요!~ FE에서 정의하는 이유가 있을까요? 궁금해서 여쭤봅니다!~

2022-06-13 06:12 UTC, austinpark420 commented on src/redux/modules/snackBar.ts
>  type Action = ReturnType<typeof show> | ReturnType<typeof hide>;
스백바를 훅으로 만드는 방법도 있을텐데 리덕스안에 만드신 이유가 있을까요?

2022-06-13 06:12 UTC, austinpark420 commented on src/pages/Login/index.tsx
> +    setCookie('accessToken', accessToken);
user.ts에 isLoggedIn 값을 state으로 관리하고있고, 쿠키에 accessToken 값을 넣고 있는데 로그인에 대한 상태를 2가지로 관리하고 있다고 생각합니다!
user.ts의 isLoggedIn 상태를 직접적으로 true, false으로 주고 있는데 setCookie를 user.ts 활용하는 방식으로 리펙토링해보면 어떨까요?

2022-06-13 06:12 UTC, austinpark420 commented on src/pages/UserInfo/index.tsx
> +  const onSubmit = async (e: React.FormEvent) => {
비밀밀번호가 일치하지 않을 때 API 통신을 안해도 되지 않을까요?!

<img width="866" alt="Screen Shot 2022-06-13 at 2 20 16 PM" src="https://user-images.githubusercontent.com/35208965/173285171-08e8853e-afcd-4ca6-a2a0-396ab420ee32.png">

2022-06-13 06:12 UTC, austinpark420 commented on src/pages/UserInfo/index.tsx
> +  const onSubmit = async (e: React.FormEvent) => {
추가로 확인버튼을 누르면 유저입장에서 비밀번호가 변경되었는지 아닌지 알수가 없는구조인것 같습니다. 스낵바를 통해 안내를 하는 등 UX에 대한 보안이 필요해 보입니다.

2022-06-13 06:12 UTC, austinpark420 commented on src/apis/user/index.ts
> +    await axios.delete(`${process.env.REACT_APP_API_URL}/api/customers/me`, {
api 통신에 대한 응답값을 변수에 담지않고 사용하는 이유가 있을까요?
해당 API 뿐 아니라 변수에 담고 안담고 어떤 기준이 있는지 궁금합니다!

2022-06-15 12:11 UTC, dayelop commented on src/App.tsx
> +        </Route>
오 이번에 처음으로 사용한 예외 처리 방식인데요~!
페이지별로 각각 redirect 처리하지 않아도 되고 어떤 페이지로의 접근이 제한되는지를 한눈에 볼 수 있어 편하더라고요 👍🏻

2022-06-15 12:48 UTC, daaaayeah commented on src/pages/Login/index.tsx
> +    const accessToken = await loginAPI(userName, password);
로그인 시 response로 status code와 accessToken을 전달하는 것으로 팀 회의를 통해 결정하였습니다
지금은 로그인을 성공한 경우에 ok status code와 함께 accessToken를 받고,
성공하지 않은 경우에는 에러 status code를 받고 있습니다

잘못된 토큰을 받는 경우는 생각하지 못했어요 😮 그럴 수도 있군요...!
잘못된 토큰을 받을 수 있는 거라면, 잘못된 로그인 성공 여부를 받을 수도 있는 건가요?!

```ts
const { data } = await axios.post(`${process.env.REACT_APP_API_URL}/api/login`, {
  userName,
  password,
});

return data.accessToken;
```

2022-06-16 02:32 UTC, daaaayeah commented on src/redux/modules/cart/cartThunk.ts
> +  (item: { id: number; imageUrl: string; name: string; price: number; isSelected: boolean }): any =>
앗 그러고 보니 msw로 모킹할 때 작성했던 코드를 사용하고 있었네요 😇
불필요한 값의 이동이 있었군요...!

상품의 id만 전달해도 장바구니에 상품 추가가 가능하므로
상품 id를 제외한 모든 값은전달하지 않는 것으로 수정하였습니다 [98cb191](https://github.com/woowacourse/react-shopping-cart-prod/pull/70/commits/98cb191cc15a5f76469dd6b079b0b98581698be9)

2022-06-16 02:42 UTC, daaaayeah commented on src/redux/modules/cart/cartThunk.ts
> +        alert(ERROR_MESSAGES.REQUEST.ADD_ITEM_TO_CART);
어떤 에러가 발생했을 때 BE는 `FE`에게 어떤 에러가 발생했는지를 알려주고,
FE는 BE로부터 받은 에러 메시지를 참고하여 `사용자`에게 어떤 에러가 발생했는지를 알려주도록 팀에서 결정하였습니다
그래서 각 BE 크루들의 에러 메시지 명세는 통일하지 않았습니다 🙂

에러 메시지 정의 방식은 회사마다 팀마다 다른 걸까요?
혹시 주로 정의하는 방식이 있을까요~?

2022-06-16 02:55 UTC, daaaayeah commented on src/pages/UserInfo/index.tsx
> +  const onSubmit = async (e: React.FormEvent) => {
앗 비밀번호 일치(비밀번호 확인)에 대한 API 통신을 말씀하시는 게 맞을까요?!
지금은 비밀번호는 API 통신으로 회원 정보의 비밀번호와 일치하는지 검사하고 비밀번호 확인은 FE에서만 검사하고 있습니다...!
비밀번호 확인을 할 때에 한 번 더 통신을 해서 검사하는 게 필요할까요~?

2022-06-16 03:00 UTC, daaaayeah commented on src/pages/UserInfo/index.tsx
> +  const onSubmit = async (e: React.FormEvent) => {
오 저도 회원 정보 수정 성공 여부를 알려주는 게 자연스럽다고 생각합니다
지금은 아무런 반응이 일어나지 않아 사용자가 답답함을 느낄 수도 있겠네요...!
회원 정보 수정에 성공하면 스낵바 메시지로 알려주는 것으로 수정하였습니다 [a5bf566](https://github.com/woowacourse/react-shopping-cart-prod/pull/70/commits/a5bf56648f79ea28e49fbd9b232bb52624ba2e83)

2022-06-19 00:32 UTC, daaaayeah commented on src/pages/ProductList/index.tsx
> +  }, [dispatch, isLoggedIn]);
useEffect 밖에서 가져다가 사용하는 모든 값은 바뀌지 않을 값이더라도 dependency에 추가하였습니다
(다시 확인해 보니 빠트린 dependency가 있어서 추가하였습니다 [2fcf51a](https://github.com/woowacourse/react-shopping-cart-prod/pull/70/commits/2fcf51a10d667f71940d9290c20ee78cb887b2e8))

이렇게 하지 않으면 eslint react-hooks/exhaustive-deps가 missing dependency 에러를 뱉더라고요 😮
[공식문서 is-it-safe-to-omit-functions-from-the-list-of-dependencies](https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies)

변화를 감지해야 하는 값만을 추가했을 때와 비교하면
혹시나 모를 에러를 방지할 수 있다는 장점이 있지만 어떤 변수의 변화를 감지하는지 바로 알 수 없다는 단점이 있다고 생각합니다

오스틴은 변화를 감지해야 하는 값만을 dependency에 추가하시나요?!
그렇게 하시는 이유도 궁금합니다 🥺

2022-06-19 00:40 UTC, daaaayeah commented on src/redux/modules/cart/cartThunk.ts
> +  (item: { id: number; imageUrl: string; name: string; price: number; isSelected: boolean }): any =>
앗 동의합니다 덕분에 다시 보니 타입 추론이 되어 별도의 타입 정의가 필요하지 않은 부분이었네요 😇
any 타입 정의 부분을 모두 지우는 것으로 수정하였습니다 [1d94d96](https://github.com/woowacourse/react-shopping-cart-prod/pull/70/commits/1d94d96eef44bb34552e308a1d46a9c392e2a831)

2022-06-19 00:46 UTC, daaaayeah commented on src/apis/user/index.ts
> +    await axios.delete(`${process.env.REACT_APP_API_URL}/api/customers/me`, {
response로 status code만을 받는 건 응답값을 따로 사용하지 않으므로 변수에 담지 않았습니다
data도 함께 받는 건 받은 data를 가공하여 사용해야 하기 때문에 변수에 담았어요 🙂

```ts
const { data } = await axios.post(`${process.env.REACT_APP_API_URL}/api/login`, {
  userName,
  password,
});

return data.accessToken;
```

2022-06-19 01:07 UTC, daaaayeah commented on src/redux/modules/snackBar.ts
>  type Action = ReturnType<typeof show> | ReturnType<typeof hide>;
스낵바는 페어가 이전에 구현했던 부분이라 이번 미션에서는 아무런 수정도 하지 않은 부분인데요~!
스낵바를 리덕스로 관리하는 이유에 대해서 아래와 같이 이야기를 나누었습니다

- 범용적 사용
- 최상단에서 렌더링
- 전역적으로 사용할 변수 필요
- 특정 컴포넌트에 종속되지 않음

2022-06-19 02:40 UTC, daaaayeah commented on src/pages/Login/index.tsx
> +    setCookie('accessToken', accessToken);
> setCookie를 user.ts 활용하는 방식

말씀하신 방식이 어떤 방식인지 잘 이해하지 못했습니다 🥲
로그인 상태를 따로 리덕스로 관리하는 것에 대해 물어봐 주신 게 맞을까요?!

이전에는 리덕스로 로그인 상태를 관리하지 않고, 쿠키 값의 유무로만 로그인 여부를 판단하려고 했습니다
로그인 상태가 바뀌더라도 컴포넌트가 리렌더링되지 않아 실시간으로 로그인 상태가 반영되지 않는다는 문제점이 있었어요 😮

따라서, 로그인 상태가 바뀔 때마다 이에 따른 리렌더링이 일어나도록 로그인 상태를 리덕스로 관리하고 있습니다
그리고 새로고침 시에도 로그인 상태가 유지되도록 쿠키를 활용하고 있어요!

2022-06-19 03:03 UTC, daaaayeah commented on src/redux/modules/cart/cartThunk.ts
> +  (item: { id: number; imageUrl: string; name: string; price: number; isSelected: boolean }): any =>
앗 any를 지양해야 한다는 것에 백 번 천 번 동의합니다

thunk에서 any 타입을 지우면 dispatch를 사용하는 곳에서 아래와 같은 에러가 뜨는데요 🥲

```
'(dispatch: AppDispatch) => Promise<void>' 형식의 인수는 'AnyAction' 형식의 매개 변수에 할당될 수 없습니다.
```

위의 에러를 없애려고 노력했으나 해결법을 찾지 못해 아직 고민 중에 있습니다
계속해서 찾아보겠습니다 언급해 주셔서 감사합니다 👍🏻

2022-06-19 09:12 UTC, austinpark420 commented on src/pages/Login/index.tsx
> +    const accessToken = await loginAPI(userName, password);
앗 status 코드가 넘어오는군요...
네트워크탭에서는 따로 확인이 안되서 값이 안내려오는줄 알았습니다. 이 부분은 무시해주셔도 될것 같습니다 🙏

2022-06-19 09:22 UTC, austinpark420 commented on src/redux/modules/snackBar.ts
>  type Action = ReturnType<typeof show> | ReturnType<typeof hide>;
이 부분은 궁금해셔 여쭤봤습니다.
정답은 없지만 hook으로 하면 리덕스로 관리하는것도 어떤 부분에서 장단점이 있을지 고민해보셔도 좋을 것 같습니다.

2022-06-19 09:25 UTC, austinpark420 commented on src/pages/UserInfo/index.tsx
> +  const onSubmit = async (e: React.FormEvent) => {
> 앗 비밀번호 일치(비밀번호 확인)에 대한 API 통신을 말씀하시는 게 맞을까요?!
지금은 비밀번호는 API 통신으로 회원 정보의 비밀번호와 일치하는지 검사하고 비밀번호 확인은 FE에서만 검사하고 있습니다...!
비밀번호 확인을 할 때에 한 번 더 통신을 해서 검사하는 게 필요할까요~?

회원정보수정에서 비밀번호가 일치하지 않을때도 API통신을 하고 있어서 비밀번호가 일치하지않을때는 API 통신을 막는건 어떤가 해서 말씀드렸습니다!

2022-06-19 09:25 UTC, austinpark420 commented on src/apis/user/index.ts
> +    await axios.delete(`${process.env.REACT_APP_API_URL}/api/customers/me`, {
오호 그렇군요!~  넵 알겠습니다 😄

2022-06-19 09:27 UTC, austinpark420 commented on src/redux/modules/cart/cartThunk.ts
> +        alert(ERROR_MESSAGES.REQUEST.ADD_ITEM_TO_CART);
회사 팀 상황마다 다 다르게 적용하고 있습니다!
어떤식으로 커뮤니케이션을 했는지 궁금해서 여쭤봤습니다 😄

2022-06-19 09:39 UTC, austinpark420 commented on src/pages/Login/index.tsx
> +    setCookie('accessToken', accessToken);
isLoggedIn의 값을 true, false으로 값을 주고 있는데 쿠기의 accessToken의 값으로 값으로 변경하는게 어떨까해서 말씀드렸습니다!~

```javascript
const userReducer = (state = initialState, action: Action) => {
  switch (action.type) {
    case LOGIN: {
      return { ...state, isLoggedIn: true };
    }
    case LOGOUT: {
      return { ...state, isLoggedIn: false };
    }
    default:
      return state;
  }
};
```

2022-06-19 09:45 UTC, austinpark420 commented on src/pages/ProductList/index.tsx
> +  }, [dispatch, isLoggedIn]);
그렇군요! 제가 redux를 사용한지 좀 되서 어떤 이유에서 궁금해서 여쭤봤습니다!~
보통 변화를 감자해야하는 값만 dependency 추가합니다.
그렇지않으면 예상치 못한 사이드 이펙트 관리가 너무 어려워서요 😢

2022-06-19 09:59 UTC, austinpark420 approved these changes
안녕하세요 티거!~

방학 잘보내고 계신가요?!
코멘트남겨주신 부분과 변경된 코드 확인했습니다 😄 
이번 미션은 여기서 머지해도 될것 같아 머지할게요!

그럼 남은 방학도 잘 보내세요!!

2022-06-19 09:59 UTC, merged